/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CtlAgenda;
import Controlador.CtlServicio;
import DTO.DtoServicio;
import Modelo.Agenda;
import Modelo.Miles;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class FrmAgenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmAgenda
     */
    CtlServicio ctlServicio;
    CtlAgenda ctlAgenda;

    public FrmAgenda() {
        initComponents();
        this.setSize(new Dimension(1150, 560));
        this.setTitle("Gestionar Agenda");
        ctlServicio = new CtlServicio();
        ctlAgenda = new CtlAgenda();
        bloquearCampos();

    }

    public void vaciarCampos() {

        txtApellidoCliente.setText("");
        txtCelularCliente.setText("");
        txtCiudadNegocio.setText("");
        txtCodigoCliente.setText("");
        txtCorreoCliente.setText("");
        txtDepartamentoNegocio.setText("");
        txtEncargadoNegocio.setText("");
        txtFechaServicio.setText("");
        txtNitNegocio.setText("");
        txtNombreCliente.setText("");
        txtNombreNegocio.setText("");
        txtObservacionServicio.setText("");
        txtPeriocidadServicio.setText("");
        txtProximaFechaServicio.setText("");
        txtTecnicoServicio.setText("");
        txtTipoCliente.setText("");
        txtTipoServicio.setText("");
        txtPagoServicio.setText("");
        txtDireccionNegocio.setText("");
        txtValorServicio.setText("");
        txtHoraAgenda.setText("");
        txtConfirmacionAgenda.setText("");
        txtObservacionesAgenda.setText("");
        txtNroFacturaServicio.setText("");

    }

    public void bloquearCampos() {

        txtApellidoCliente.setEditable(false);
        txtCelularCliente.setEditable(false);
        txtCiudadNegocio.setEditable(false);
        txtCodigoCliente.setEditable(false);
        txtCorreoCliente.setEditable(false);
        txtDepartamentoNegocio.setEditable(false);
        txtEncargadoNegocio.setEditable(false);
        txtFechaServicio.setEditable(false);
        txtNitNegocio.setEditable(false);
        txtNombreCliente.setEditable(false);
        txtNombreNegocio.setEditable(false);
        txtObservacionServicio.setEditable(false);
        txtPeriocidadServicio.setEditable(false);
        txtProximaFechaServicio.setEditable(false);
        txtTecnicoServicio.setEditable(false);
        txtTipoCliente.setEditable(false);
        txtTipoServicio.setEditable(false);
        txtPagoServicio.setEditable(false);
        txtDireccionNegocio.setEditable(false);
        txtValorServicio.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNroFacturaServicio = new javax.swing.JTextField();
        txtTipoServicio = new javax.swing.JTextField();
        txtTecnicoServicio = new javax.swing.JTextField();
        txtFechaServicio = new javax.swing.JTextField();
        txtPeriocidadServicio = new javax.swing.JTextField();
        txtProximaFechaServicio = new javax.swing.JTextField();
        txtPagoServicio = new javax.swing.JTextField();
        txtValorServicio = new javax.swing.JTextField();
        txtObservacionServicio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        txtTipoCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidoCliente = new javax.swing.JTextField();
        txtCorreoCliente = new javax.swing.JTextField();
        txtCelularCliente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNombreNegocio = new javax.swing.JTextField();
        txtDireccionNegocio = new javax.swing.JTextField();
        txtNitNegocio = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtEncargadoNegocio = new javax.swing.JTextField();
        txtDepartamentoNegocio = new javax.swing.JTextField();
        txtCiudadNegocio = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtHoraAgenda = new javax.swing.JTextField();
        txtConfirmacionAgenda = new javax.swing.JTextField();
        txtObservacionesAgenda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        BtnServicio = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gestionar Agenda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nro Factura");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tipo de Servicio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 123, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tecnico");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 173, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Fecha de Realizo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 223, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Periocidad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 273, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Proxima Fecha");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 323, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Pago");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 373, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Valor");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 423, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Observacion");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 473, -1, -1));

        txtNroFacturaServicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNroFacturaServicioKeyTyped(evt);
            }
        });
        getContentPane().add(txtNroFacturaServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 180, -1));
        getContentPane().add(txtTipoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 180, -1));
        getContentPane().add(txtTecnicoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 180, -1));
        getContentPane().add(txtFechaServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 180, -1));
        getContentPane().add(txtPeriocidadServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 180, -1));
        getContentPane().add(txtProximaFechaServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 180, -1));
        getContentPane().add(txtPagoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 180, -1));
        getContentPane().add(txtValorServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 180, -1));
        getContentPane().add(txtObservacionServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 180, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Codigo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 73, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Tipo de Cliente");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 123, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Nombre");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 173, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Apellido");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 223, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Correo");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 273, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Celular");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 323, -1, -1));
        getContentPane().add(txtCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 180, -1));
        getContentPane().add(txtTipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 180, -1));
        getContentPane().add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 180, -1));
        getContentPane().add(txtApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 180, -1));
        getContentPane().add(txtCorreoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 180, -1));
        getContentPane().add(txtCelularCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 180, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Nombre Del Negocio");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 373, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Direccion");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 423, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Nit");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 473, -1, -1));
        getContentPane().add(txtNombreNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 180, -1));
        getContentPane().add(txtDireccionNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 180, -1));
        getContentPane().add(txtNitNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 180, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Encargado");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 73, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Departamento");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 123, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Ciudad");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 173, -1, -1));
        getContentPane().add(txtEncargadoNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 180, -1));
        getContentPane().add(txtDepartamentoNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 180, -1));
        getContentPane().add(txtCiudadNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 180, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Hora");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 223, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Confirmacion");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 273, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Observaciones");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 323, -1, -1));
        getContentPane().add(txtHoraAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, 180, -1));
        getContentPane().add(txtConfirmacionAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, 180, -1));
        getContentPane().add(txtObservacionesAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, 180, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 370, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 370, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(965, 370, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1045, 370, -1, -1));

        BtnServicio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnServicio.setText("Buscar Servicio");
        BtnServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnServicioActionPerformed(evt);
            }
        });
        getContentPane().add(BtnServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String nroFactura, fecha, hora, confimacion, observacion;

        nroFactura = txtNroFacturaServicio.getText();
        fecha = txtFechaServicio.getText();
        hora = txtHoraAgenda.getText();
        confimacion = txtConfirmacionAgenda.getText();
        observacion = txtObservacionesAgenda.getText();

        if (nroFactura.isEmpty() || hora.isEmpty() || confimacion.isEmpty()
                || observacion.isEmpty() || fecha.isEmpty()) {

            JOptionPane.showMessageDialog(null, "porfavor llene los datos");

        } else {

            try {

                
/*                ctlAgenda.guardarAgenda(agenda, nroFactura);
                JOptionPane.showMessageDialog(null, "Se ha guardado correctamente");
                vaciarCampos();*/

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String factura, fecha;

        factura = txtNroFacturaServicio.getText();
        fecha = txtFechaServicio.getText();

        if (factura.isEmpty() || fecha.isEmpty()) {

            JOptionPane.showMessageDialog(null, "por favor busque por la factura");

        } else {

            try {

                /*
                Agenda agenda = ctlAgenda.buscarAgenda(factura, fecha);
                txtHoraAgenda.setText(agenda.getHora());
                txtConfirmacionAgenda.setText(agenda.getConfirmacion());
                txtObservacionesAgenda.setText(agenda.getObservacion());
*/
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String nroFactura, fecha, hora, confimacion, observacion;

        nroFactura = txtNroFacturaServicio.getText();
        fecha = txtFechaServicio.getText();
        hora = txtHoraAgenda.getText();
        confimacion = txtConfirmacionAgenda.getText();
        observacion = txtObservacionesAgenda.getText();

        if (nroFactura.isEmpty() || hora.isEmpty() || confimacion.isEmpty()
                || observacion.isEmpty() || fecha.isEmpty()) {

            JOptionPane.showMessageDialog(null, "porfavor llene los datos");

        } else {

            try {
/*
                Agenda agenda = new Agenda(0, 0, hora, confimacion, observacion);
                ctlAgenda.edtarAgenda(agenda, nroFactura);
                JOptionPane.showMessageDialog(null, "Se ha editado correctamente");
                vaciarCampos();
*/
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        String factura, fecha;

        factura = txtNroFacturaServicio.getText();
        fecha = txtFechaServicio.getText();

        if (factura.isEmpty() || fecha.isEmpty()) {

            JOptionPane.showMessageDialog(null, "por favor busque por la factura");

        } else {

            try {

                ctlAgenda.eliminarAgenda(factura, fecha);
                vaciarCampos();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void BtnServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnServicioActionPerformed
        // TODO add your handling code here:

        int valor;
        String nroFactura, valorCadena;

        nroFactura = txtNroFacturaServicio.getText();

        if (nroFactura.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Por favor busque por el numero "
                    + "de la factura Registrada");

        } else {

            try {

                DtoServicio dtoServicio = ctlServicio.buscarDtoServicio(nroFactura);

                txtApellidoCliente.setText(dtoServicio.getApellido());
                txtCelularCliente.setText(dtoServicio.getCelular());
                txtCiudadNegocio.setText(dtoServicio.getCiudad());
                txtCodigoCliente.setText(dtoServicio.getCodigo());
                txtCorreoCliente.setText(dtoServicio.getCorreo());
                txtDepartamentoNegocio.setText(dtoServicio.getMunicipio());
                txtEncargadoNegocio.setText(dtoServicio.getEncargado());
                txtFechaServicio.setText(dtoServicio.getFecha());
                txtNitNegocio.setText(dtoServicio.getNit());
                txtNombreCliente.setText(dtoServicio.getNombre());
                txtNombreNegocio.setText(dtoServicio.getNombreNegocio());
                txtObservacionServicio.setText(dtoServicio.getObservacion());
                txtPeriocidadServicio.setText(dtoServicio.getPeriocidad());
                txtProximaFechaServicio.setText(dtoServicio.getProxFecha());
                txtTecnicoServicio.setText(dtoServicio.getTecnico());
                txtTipoCliente.setText(dtoServicio.getTipo());
                txtTipoServicio.setText(dtoServicio.getTipoServicio());
                txtPagoServicio.setText(dtoServicio.getPago());
                txtDireccionNegocio.setText(dtoServicio.getDireccion());

                Miles m = new Miles();
                valor = Integer.parseInt(dtoServicio.getValor());
                valorCadena = m.separarMiles(valor);
                txtValorServicio.setText(valorCadena);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }//GEN-LAST:event_BtnServicioActionPerformed

    private void txtNroFacturaServicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroFacturaServicioKeyTyped
        // TODO add your handling code here:

        char enter = evt.getKeyChar();

        if (enter == KeyEvent.VK_ENTER) {

            BtnServicio.doClick();

        }
    }//GEN-LAST:event_txtNroFacturaServicioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnServicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JTextField txtCelularCliente;
    private javax.swing.JTextField txtCiudadNegocio;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtConfirmacionAgenda;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtDepartamentoNegocio;
    private javax.swing.JTextField txtDireccionNegocio;
    private javax.swing.JTextField txtEncargadoNegocio;
    private javax.swing.JTextField txtFechaServicio;
    private javax.swing.JTextField txtHoraAgenda;
    private javax.swing.JTextField txtNitNegocio;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreNegocio;
    private javax.swing.JTextField txtNroFacturaServicio;
    private javax.swing.JTextField txtObservacionServicio;
    private javax.swing.JTextField txtObservacionesAgenda;
    private javax.swing.JTextField txtPagoServicio;
    private javax.swing.JTextField txtPeriocidadServicio;
    private javax.swing.JTextField txtProximaFechaServicio;
    private javax.swing.JTextField txtTecnicoServicio;
    private javax.swing.JTextField txtTipoCliente;
    private javax.swing.JTextField txtTipoServicio;
    private javax.swing.JTextField txtValorServicio;
    // End of variables declaration//GEN-END:variables
}
