/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CtlCliente;
import Modelo.Cliente;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALAN
 */
public class FrmCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCliente
     */
    CtlCliente ctlCliente;

    public FrmCliente() {
        initComponents();
        this.setSize(new Dimension(530, 500));
        this.setTitle("Gestionar Usuarios");
        cargarCombo();
        ctlCliente = new CtlCliente();
        buscarUltimoCodigo();
    }

    public void cargarCombo() {

        cbTipo.removeAllItems();
        cbTipo.addItem("Seleccione");
        cbTipo.addItem("Comercial");
        cbTipo.addItem("Residencial");
    }

    public void limpiarCampos() {

        txtApellidoClienmte.setText("");
        txtCodigo.setText("");
        txtNombreCliente.setText("");
        txtCelular.setText("");
        txtCorreo.setText("");
        cargarCombo();

    }

    public void buscarUltimoCodigo() {

        int consecutivo;
        String letra1, numero, codigoCadena;

        Cliente cliente = ctlCliente.buscarUltimoRegistroCliente();

        String[] separarTodo = cliente.getCodigo().split("C");

        if (separarTodo.length > 1) {

            letra1 = separarTodo[0];
            numero = separarTodo[1];

            consecutivo = Integer.parseInt(numero) + 1;

            codigoCadena = "C" + consecutivo;
            txtCodigo.setText(codigoCadena);

        } else {

            System.out.println("nada");

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidoClienmte = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCliente = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gestionar Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Codigo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tipo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 123, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 173, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Apellido");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 223, -1, -1));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));
        getContentPane().add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 150, -1));
        getContentPane().add(txtApellidoClienmte, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 150, -1));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 150, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 273, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 273, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 273, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 273, -1, -1));

        tbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Tipo", "Nombre", "Apellido", "Celular", "Correo"
            }
        ));
        tbCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 323, 480, 130));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("celular");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 73, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Correo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 123, -1, -1));
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 150, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String codigo, tipo, nombre, apellido, celular, correo;

        codigo = txtCodigo.getText();
        tipo = (String) cbTipo.getSelectedItem();
        nombre = txtNombreCliente.getText();
        apellido = txtApellidoClienmte.getText();
        celular = txtCelular.getText();
        correo = txtCorreo.getText();

        if (codigo.isEmpty() || tipo.equals("Seleccione") || nombre.isEmpty()
                || apellido.isEmpty() || celular.isEmpty() || correo.isEmpty()) {

            JOptionPane.showMessageDialog(null, "por favor llenar los datos");

        } else {

            try {

                Cliente cliente = new Cliente(0, codigo, tipo, nombre, apellido, celular, correo);
                ctlCliente.guardarCliente(cliente);
                JOptionPane.showMessageDialog(null, "se ha guardado correctamente");
                limpiarCampos();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String codigo, nombre;

        codigo = txtCodigo.getText();
        nombre = txtNombreCliente.getText();

        if (codigo.isEmpty() && nombre.isEmpty()) {

            JOptionPane.showMessageDialog(null, "busque por codigo, nombre o apellido");

        } else if (codigo.isEmpty()) {

            try {

                ArrayList<Cliente> lista = ctlCliente.listarClientePorFiltro("nombre", nombre);

                DefaultTableModel modelo = (DefaultTableModel) tbCliente.getModel();
                modelo.setRowCount(0);

                for (Cliente cliente : lista) {

                    modelo.addRow(new Object[]{cliente.getCodigo(), cliente.getTipo(),
                        cliente.getNombre(), cliente.getApellido(), cliente.getCelular(),
                        cliente.getCorreo()});

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        } else if (nombre.isEmpty()) {

            try {

                ArrayList<Cliente> lista = ctlCliente.listarClientePorFiltro("codigo", codigo);

                DefaultTableModel modelo = (DefaultTableModel) tbCliente.getModel();
                modelo.setRowCount(0);

                for (Cliente cliente : lista) {

                    modelo.addRow(new Object[]{cliente.getCodigo(), cliente.getTipo(),
                        cliente.getNombre(), cliente.getApellido(), cliente.getCelular(),
                        cliente.getCorreo()});

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String codigo, tipo, nombre, apellido, celular, correo;

        codigo = txtCodigo.getText();
        tipo = (String) cbTipo.getSelectedItem();
        nombre = txtNombreCliente.getText();
        apellido = txtApellidoClienmte.getText();
        celular = txtCelular.getText();
        correo = txtCorreo.getText();

        if (codigo.isEmpty() || tipo.equals("Seleccione") || nombre.isEmpty()
                || apellido.isEmpty()) {

            JOptionPane.showMessageDialog(null, "por favor llenar los datos");

        } else {

            try {

                Cliente cliente = new Cliente(0, codigo, tipo, nombre, apellido, celular, correo);
                ctlCliente.editarCliente(cliente);
                JOptionPane.showMessageDialog(null, "se ha editado correctamente");
                limpiarCampos();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        String codigo;

        codigo = txtCodigo.getText();

        if (codigo.isEmpty()) {

            JOptionPane.showMessageDialog(null, "por favor buscar al cliente y despues lo elimina");

        } else {

            ctlCliente.eliminarCliente(codigo);
            JOptionPane.showMessageDialog(null, "se ha eliminado correctamente");
            limpiarCampos();

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void tbClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClienteMouseClicked
        // TODO add your handling code here:

        int seleccionar;

        seleccionar = tbCliente.rowAtPoint(evt.getPoint());

        txtCodigo.setText(String.valueOf(tbCliente.getValueAt(seleccionar, 0)));
        txtNombreCliente.setText(String.valueOf(tbCliente.getValueAt(seleccionar, 2)));
        txtApellidoClienmte.setText(String.valueOf(tbCliente.getValueAt(seleccionar, 3)));
        txtCelular.setText(String.valueOf(tbCliente.getValueAt(seleccionar, 4)));
        txtCorreo.setText(String.valueOf(tbCliente.getValueAt(seleccionar, 5)));
    }//GEN-LAST:event_tbClienteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCliente;
    private javax.swing.JTextField txtApellidoClienmte;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
