/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CtlInventario;
import Modelo.Inventario;
import Modelo.Miles;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class FrmInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmInventario
     */
    CtlInventario ctlInventario;

    public FrmInventario() {
        initComponents();
        this.setSize(new Dimension(750, 400));
        this.setTitle("Gestionar Inventario");
        ctlInventario = new CtlInventario();
    }

    public void vaciarCampos() {

        txtCantidad.setText("");
        txtNombreProducto.setText("");
        txtNroLote.setText("");
        txtValor.setText("");
        jcFechaVencimiento.setCalendar(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtNombreProducto = new javax.swing.JTextField();
        txtNroLote = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcFechaVencimiento = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gestion Inventario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre del Producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nro Lote");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 123, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Valor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 173, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));
        getContentPane().add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 180, -1));
        getContentPane().add(txtNroLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 180, -1));

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorKeyReleased(evt);
            }
        });
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Fecha de vencimiento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 223, -1, -1));

        jcFechaVencimiento.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jcFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 180, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Agregar Stock");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Retirar Stock");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 120, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cantidad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 273, -1, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 180, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Descripcion");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 73, -1, -1));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Cantidad");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 123, -1, -1));
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        int cantidad, valor, stock;
        String nombreProducto, nroLote, fechaVencimiento, valorCadena, descripcion;

        nombreProducto = txtNombreProducto.getText();
        nroLote = txtNroLote.getText();
        fechaVencimiento = ((JTextField) jcFechaVencimiento.getDateEditor().getUiComponent()).getText();
        valorCadena = txtValor.getText();
        cantidad = Integer.parseInt(txtCantidad.getText());
        descripcion = txtDescripcion.getText();
        stock = Integer.parseInt(txtStock.getText());

        if (nombreProducto.isEmpty() || nroLote.isEmpty() || fechaVencimiento.isEmpty()
                || cantidad == 0 || valorCadena.isEmpty() || descripcion.isEmpty() || stock == 0) {

            JOptionPane.showMessageDialog(null, "por favor llene los campos");

        } else {

            try {

                String num = valorCadena.replace(".", "");
                valor = Integer.parseInt(num);

                Inventario inventario = new Inventario(0, cantidad, valor,
                        nombreProducto, nroLote, fechaVencimiento);

                ctlInventario.agregarStock(inventario, stock, descripcion);
                JOptionPane.showMessageDialog(null, "se ha Ingresado correctamente");
                vaciarCampos();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int cantidad, valor;
        String nombreProducto, nroLote, fechaVencimiento, valorCadena;

        nombreProducto = txtNombreProducto.getText();
        nroLote = txtNroLote.getText();
        fechaVencimiento = ((JTextField) jcFechaVencimiento.getDateEditor().getUiComponent()).getText();
        valorCadena = txtValor.getText();
        cantidad = Integer.parseInt(txtCantidad.getText());

        if (nombreProducto.isEmpty() || nroLote.isEmpty() || fechaVencimiento.isEmpty()
                || cantidad == 0 || valorCadena.isEmpty()) {

            JOptionPane.showMessageDialog(null, "por favor llene los campos");

        } else {

            try {

                String num = valorCadena.replace(".", "");
                valor = Integer.parseInt(num);

                Inventario inventario = new Inventario(0, cantidad, valor,
                        nombreProducto, nroLote, fechaVencimiento);

                ctlInventario.guardarInventario(inventario);
                JOptionPane.showMessageDialog(null, "se ha guardado correctamente");
                vaciarCampos();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyReleased
        // TODO add your handling code here:

        Miles op = new Miles();

        if (!txtValor.getText().isEmpty()) {

            double numero;
            String num = txtValor.getText();
            String numeracion = num.replace(".", "");
            numero = Double.parseDouble(numeracion);
            txtValor.setText(op.separarMiles(numero));

        } else {
            txtValor.setText("");
        }
    }//GEN-LAST:event_txtValorKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Date fecha;
        int valor1;
        String nroLote, fecha1, valor;

        nroLote = txtNroLote.getText();

        if (nroLote.isEmpty()) {

            JOptionPane.showMessageDialog(null, "por favor busque por nro de lote");

        } else {
            try {

                Miles miles = new Miles();
                SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

                Inventario inventario = ctlInventario.buscarInventario(nroLote);

                txtCantidad.setText(inventario.getCantidad() + "");
                txtNombreProducto.setText(inventario.getNombreProducto());
                txtNroLote.setText(inventario.getNroLote());

                valor1 = inventario.getValor();
                valor = miles.separarMiles(valor1);
                txtValor.setText(valor);

                fecha1 = inventario.getFechaVencimiento();
                fecha = format.parse(fecha1);
                jcFechaVencimiento.setDate(fecha);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int cantidad, valor;
        String nombreProducto, nroLote, fechaVencimiento, valorCadena;

        nombreProducto = txtNombreProducto.getText();
        nroLote = txtNroLote.getText();
        fechaVencimiento = ((JTextField) jcFechaVencimiento.getDateEditor().getUiComponent()).getText();
        valorCadena = txtValor.getText();
        cantidad = Integer.parseInt(txtCantidad.getText());

        if (nombreProducto.isEmpty() || nroLote.isEmpty() || fechaVencimiento.isEmpty()
                || cantidad == 0 || valorCadena.isEmpty()) {

            JOptionPane.showMessageDialog(null, "por favor llene los campos");

        } else {

            try {

                String num = valorCadena.replace(".", "");
                valor = Integer.parseInt(num);

                Inventario inventario = new Inventario(0, cantidad, valor,
                        nombreProducto, nroLote, fechaVencimiento);

                ctlInventario.editarInventario(inventario);
                JOptionPane.showMessageDialog(null, "se ha editado correctamente");
                vaciarCampos();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        String nroLote;

        nroLote = txtNroLote.getText();

        if (nroLote.isEmpty()) {

            JOptionPane.showMessageDialog(null, "por favor busque el producto por el"
                    + "nro de lote y el da al boton eliminar");

        } else {
            try {

                ctlInventario.eliminarInventario(nroLote);
                JOptionPane.showMessageDialog(null, "se ha eliminado correctamente");
                vaciarCampos();

            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int cantidad, valor, stock;
        String nombreProducto, nroLote, fechaVencimiento, valorCadena, descripcion;

        nombreProducto = txtNombreProducto.getText();
        nroLote = txtNroLote.getText();
        fechaVencimiento = ((JTextField) jcFechaVencimiento.getDateEditor().getUiComponent()).getText();
        valorCadena = txtValor.getText();
        cantidad = Integer.parseInt(txtCantidad.getText());
        descripcion = txtDescripcion.getText();
        stock = Integer.parseInt(txtStock.getText());

        if (nombreProducto.isEmpty() || nroLote.isEmpty() || fechaVencimiento.isEmpty()
                || cantidad == 0 || valorCadena.isEmpty() || descripcion.isEmpty() || stock == 0) {

            JOptionPane.showMessageDialog(null, "por favor llene los campos");

        } else {

            try {

                String num = valorCadena.replace(".", "");
                valor = Integer.parseInt(num);

                Inventario inventario = new Inventario(0, cantidad, valor,
                        nombreProducto, nroLote, fechaVencimiento);

                ctlInventario.eliminarStock(inventario, stock, descripcion);
                JOptionPane.showMessageDialog(null, "se ha Ingresado correctamente");
                vaciarCampos();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.toedter.calendar.JDateChooser jcFechaVencimiento;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtNroLote;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
