/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CtlInventario;
import DTO.DtoInventarioEntradas;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class FrmListaInventarioEntradas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmListaInventarioEntradas
     */
    CtlInventario ctlInventario;

    public FrmListaInventarioEntradas() {
        initComponents();
        this.setSize(new Dimension(1000, 500));
        this.setTitle("Lista Inventario de Entradas");
        ctlInventario = new CtlInventario();
        listar();
    }

    public void listar() {

        ArrayList<DtoInventarioEntradas> lista = ctlInventario.listaInventarioEntradas();

        DefaultTableModel modelo = (DefaultTableModel) tbInventario.getModel();
        modelo.setRowCount(0);

        for (DtoInventarioEntradas dtoInventarioEntradas : lista) {

            modelo.addRow(new Object[]{dtoInventarioEntradas.getNroLote(),
                dtoInventarioEntradas.getNombreProducto(), dtoInventarioEntradas.getFechaVencimiento(),
                dtoInventarioEntradas.getDescripcion(), dtoInventarioEntradas.getFecha(),
                dtoInventarioEntradas.getCantidad(), dtoInventarioEntradas.getTotalValor()});

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbColumna = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcFecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInventario = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Columna");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Lista Inventario de Entradas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        cbColumna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Nro de Lote", "Nombre del Producto", "Fecha de Vencimiento", "Descripcion", "Fecha", "Cantidad", "Total Valor" }));
        cbColumna.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbColumnaItemStateChanged(evt);
            }
        });
        getContentPane().add(cbColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Dato");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 73, -1, -1));
        getContentPane().add(txtDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 70, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 73, -1, -1));

        jcFecha.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 150, -1));

        tbInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nro de Lote", "Nombre del Producto", "Fecha de Vencimiento", "Descripcion", "Fecha", "Cantidad", "Total valor"
            }
        ));
        jScrollPane1.setViewportView(tbInventario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 960, 340));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Filtar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Exportar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbColumnaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbColumnaItemStateChanged
        // TODO add your handling code here:

        String datoSeleccionado;

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            datoSeleccionado = (String) evt.getItem();

            if (datoSeleccionado.equals("Fecha de Vencimiento")) {

                jcFecha.setEnabled(true);
                txtDato.setEnabled(false);

            } else if (datoSeleccionado.equals("Fecha")) {

                jcFecha.setEnabled(true);
                txtDato.setEnabled(false);

            } else {

                txtDato.setEnabled(true);
                jcFecha.setEnabled(false);

            }
        }
    }//GEN-LAST:event_cbColumnaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String columna, dato, fecha;

        columna = (String) cbColumna.getSelectedItem();

        if (columna.equals("Seleccione")) {
            JOptionPane.showMessageDialog(null, "ingrese un dato o una fecha");
        } else {

            try {

                if (columna.equals("Fecha de Vencimiento")) {

                    fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();

                    ArrayList<DtoInventarioEntradas> lista = ctlInventario.listaInventarioEntardaFiltro(columna, fecha);

                    DefaultTableModel modelo = (DefaultTableModel) tbInventario.getModel();
                    modelo.setRowCount(0);

                    for (DtoInventarioEntradas dtoInventarioEntradas : lista) {

                        modelo.addRow(new Object[]{dtoInventarioEntradas.getNroLote(),
                            dtoInventarioEntradas.getNombreProducto(), dtoInventarioEntradas.getFechaVencimiento(),
                            dtoInventarioEntradas.getDescripcion(), dtoInventarioEntradas.getFecha(),
                            dtoInventarioEntradas.getCantidad(), dtoInventarioEntradas.getTotalValor()});

                    }

                } else if (columna.equals("Fecha")) {

                    fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();

                    ArrayList<DtoInventarioEntradas> lista = ctlInventario.listaInventarioEntardaFiltro(columna, fecha);

                    DefaultTableModel modelo = (DefaultTableModel) tbInventario.getModel();
                    modelo.setRowCount(0);

                    for (DtoInventarioEntradas dtoInventarioEntradas : lista) {

                        modelo.addRow(new Object[]{dtoInventarioEntradas.getNroLote(),
                            dtoInventarioEntradas.getNombreProducto(), dtoInventarioEntradas.getFechaVencimiento(),
                            dtoInventarioEntradas.getDescripcion(), dtoInventarioEntradas.getFecha(),
                            dtoInventarioEntradas.getCantidad(), dtoInventarioEntradas.getTotalValor()});

                    }

                } else {

                    dato = txtDato.getText();

                    ArrayList<DtoInventarioEntradas> lista = ctlInventario.listaInventarioEntardaFiltro(columna, dato);

                    DefaultTableModel modelo = (DefaultTableModel) tbInventario.getModel();
                    modelo.setRowCount(0);

                    for (DtoInventarioEntradas dtoInventarioEntradas : lista) {

                        modelo.addRow(new Object[]{dtoInventarioEntradas.getNroLote(),
                            dtoInventarioEntradas.getNombreProducto(), dtoInventarioEntradas.getFechaVencimiento(),
                            dtoInventarioEntradas.getDescripcion(), dtoInventarioEntradas.getFecha(),
                            dtoInventarioEntradas.getCantidad(), dtoInventarioEntradas.getTotalValor()});

                    }

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();
        
        if (fecha.isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "si desea exportar busque por fecha");
            
        }else{
            
            try {
                
                ctlInventario.reporteInventarioEntradas(fecha);
                JOptionPane.showMessageDialog(null, "inventario de las entradas generado");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbColumna;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jcFecha;
    private javax.swing.JTable tbInventario;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
