/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CtlCliente;
import Modelo.Cliente;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALAN
 */
public class FrmListaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmListaCliente
     */
    CtlCliente ctlCliente;

    public FrmListaCliente() {
        initComponents();
        this.setSize(new Dimension(1250, 650));
        this.setTitle("Lista Clientes");
        ctlCliente = new CtlCliente();
        listarCliente();

    }

    public void listarCliente() {

        ArrayList<Cliente> lista = ctlCliente.listarCliente();

        DefaultTableModel modelo = (DefaultTableModel) tbCliente.getModel();
        modelo.setRowCount(0);

        for (Cliente cliente : lista) {

            modelo.addRow(new Object[]{cliente.getCodigo(), cliente.getTipo(),
                cliente.getNombre(), cliente.getApellido(), cliente.getCelular(),
                cliente.getCorreo()});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcColumna = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCliente = new javax.swing.JTable();
        BtnFiltrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Lista Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Columna");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        jcColumna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Codigo", "Tipo", "Nombre", "Apellido", "Celular", "Correo" }));
        getContentPane().add(jcColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Dato");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 73, -1, -1));

        txtDato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatoKeyTyped(evt);
            }
        });
        getContentPane().add(txtDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 150, -1));

        tbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Tipo", "Nombre", "Apellido", "Celular", "Correo"
            }
        ));
        jScrollPane1.setViewportView(tbCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1210, 490));

        BtnFiltrar.setText("Filtrar");
        BtnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 67, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFiltrarActionPerformed
        // TODO add your handling code here:

        String columna, dato;

        columna = (String) jcColumna.getSelectedItem();
        dato = txtDato.getText();

        if (columna.equals("Seleccione") || dato.isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "seleccione una columna y llene el campo dato");

        } else {

            ArrayList<Cliente> lista = ctlCliente.llenarLista(columna, dato);

            DefaultTableModel modelo = (DefaultTableModel) tbCliente.getModel();
            modelo.setRowCount(0);

            for (Cliente cliente : lista) {

                modelo.addRow(new Object[]{cliente.getCodigo(), cliente.getTipo(),
                    cliente.getNombre(), cliente.getApellido(), cliente.getCelular(),
                    cliente.getCorreo()});

            }

        }

    }//GEN-LAST:event_BtnFiltrarActionPerformed

    private void txtDatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoKeyTyped
        // TODO add your handling code here:

        char enter = evt.getKeyChar();

        if (enter == KeyEvent.VK_ENTER) {

            BtnFiltrar.doClick();

        }
    }//GEN-LAST:event_txtDatoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFiltrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcColumna;
    private javax.swing.JTable tbCliente;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
