/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CtlCliente;
import Controlador.CtlLocal;
import DTO.DTOLocal;
import Modelo.Ciudad;
import Modelo.Cliente;
import Modelo.Local;
import Modelo.Municipio;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.time.temporal.TemporalQueries;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.eclipse.jdt.internal.compiler.lookup.ElementValuePair;

/**
 *
 * @author ALAN
 */
public class FrmLocales extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmLocales
     */
    String ciudadEditar, direccionActual;
    CtlLocal ctlLocal;
    CtlCliente ctlCliente;

    public FrmLocales() {
        initComponents();
        this.setSize(new Dimension(690, 635));
        this.setTitle("Gestionar Locales");
        ctlLocal = new CtlLocal();
        ctlCliente = new CtlCliente();
        llenarComboMunicipio();
    }

    public void llenarComboMunicipio() {

        ArrayList<Municipio> lista = ctlLocal.cargarMunicipio();

        jcDepartamento.removeAllItems();
        jcDepartamento.addItem("Seleccione");

        jcCiudad.removeAllItems();
        jcCiudad.addItem("Seleccione");

        for (Municipio municipio : lista) {

            jcDepartamento.addItem(municipio.getNombre());

        }

    }

    public void limpiarCampos() {

        txtNombreNegocio.setText("");
        txtDireccion.setText("");
        txtNit.setText("");
        txtEncargado.setText("");
        llenarComboMunicipio();

    }

    public void listaLocales(String codigo) {

        ArrayList<DTOLocal> lista = ctlLocal.listarLocalPorCliente(codigo);

        DefaultTableModel modelo = (DefaultTableModel) tbLocal.getModel();
        modelo.setRowCount(0);

        for (DTOLocal dTOLocal : lista) {

            modelo.addRow(new Object[]{dTOLocal.getNombreNegocio(), dTOLocal.getDireccion(),
                dTOLocal.getNit(), dTOLocal.getEncargado(), dTOLocal.getMunicipio(), dTOLocal.getCiudad()});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTipoCliente = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNombreNegocio = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtNit = new javax.swing.JTextField();
        txtEncargado = new javax.swing.JTextField();
        jcDepartamento = new javax.swing.JComboBox<>();
        jcCiudad = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLocal = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gestionar Locales");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Codigo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tipo de Cliente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 123, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 173, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Apellido");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 223, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Correo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 273, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Celular");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 323, -1, -1));
        getContentPane().add(txtTipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 120, 150, -1));

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 70, 150, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 170, 150, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 220, 150, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 270, 150, -1));
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 320, 150, -1));

        btnBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscarCliente.setText("Buscar Cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 373, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Nombre del Negocio");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 73, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Direccion");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 123, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nit");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 173, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Encargado");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 223, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Departamento");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 273, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Ciudad");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 323, -1, -1));
        getContentPane().add(txtNombreNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 150, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 150, -1));
        getContentPane().add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 150, -1));
        getContentPane().add(txtEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 150, -1));

        jcDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcDepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcDepartamentoItemStateChanged(evt);
            }
        });
        getContentPane().add(jcDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 150, -1));

        jcCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 150, -1));

        tbLocal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Direccion", "Nit", "Encargado", "Municipio", "Ciudad"
            }
        ));
        tbLocal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLocalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLocal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 640, 170));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 370, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcDepartamentoItemStateChanged
        // TODO add your handling code here:

        String datoSeleccionado;

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            datoSeleccionado = (String) evt.getItem();

            if (datoSeleccionado.equals("Seleccione")) {

            } else {

                jcCiudad.removeAllItems();
                jcCiudad.addItem("Seleccione");

                ArrayList<Ciudad> lista = ctlLocal.cargarCiudad(datoSeleccionado);

                for (Ciudad ciudad : lista) {

                    jcCiudad.addItem(ciudad.getNombre());

                }

            }
        }
    }//GEN-LAST:event_jcDepartamentoItemStateChanged

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:

        String codigo;

        codigo = txtCodigo.getText();

        if (codigo.isEmpty()) {

            JOptionPane.showMessageDialog(null, "por favor busque por codigo al cliente");

        } else {

            try {

                Cliente c = ctlCliente.buscarCliente(codigo);

                txtApellido.setText(c.getApellido());
                txtCelular.setText(c.getCelular());
                txtCorreo.setText(c.getCorreo());
                txtNombre.setText(c.getNombre());
                txtTipoCliente.setText(c.getTipo());

                listaLocales(codigo);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }


    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String nombreNegocio, direccion, nit, encargado, codigo, ciudad;

        nombreNegocio = txtNombreNegocio.getText();
        direccion = txtDireccion.getText();
        nit = txtNit.getText();
        encargado = txtEncargado.getText();
        codigo = txtCodigo.getText();
        ciudad = (String) jcCiudad.getSelectedItem();

        if (nombreNegocio.isEmpty() || direccion.isEmpty() || nit.isEmpty()
                || encargado.isEmpty() || codigo.isEmpty() || ciudad.equals("Seleccione")) {

            JOptionPane.showMessageDialog(null, "porfavor llenar los "
                    + "datos del local que quiere registrar");
        } else {

            try {

                Local local = new Local(0, 0, 0, nombreNegocio, direccion, nit, encargado);
                ctlLocal.guardarLocal(local, ciudad, codigo);
                JOptionPane.showMessageDialog(null, "se ha guardado correctamente");
                listaLocales(codigo);
                limpiarCampos();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String nombreNegocio, direccion, nit, encargado, codigo, ciudad;

        nombreNegocio = txtNombreNegocio.getText();
        direccion = txtDireccion.getText();
        nit = txtNit.getText();
        encargado = txtEncargado.getText();
        codigo = txtCodigo.getText();
        ciudad = (String) jcCiudad.getSelectedItem();

        if (nombreNegocio.isEmpty() || direccion.isEmpty() || nit.isEmpty()
                || encargado.isEmpty() || codigo.isEmpty() || ciudad.equals("Seleccione")) {

            JOptionPane.showMessageDialog(null, "porfavor llenar los "
                    + "datos del local que quiere registrar");
        } else {

            try {

                Local local = new Local(0, 0, 0, nombreNegocio, direccion, nit, encargado);
                ctlLocal.editarLocal(local, ciudad, codigo, ciudadEditar, direccionActual);
                JOptionPane.showMessageDialog(null, "se ha editado correctamente");
                listaLocales(codigo);
                limpiarCampos();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        String direccion, ciudad, codigo;

        direccion = txtDireccion.getText();
        codigo = txtCodigo.getText();

        if (direccion.isEmpty()) {

            JOptionPane.showMessageDialog(null, "porfavor llenar los "
                    + "datos del local que quiere registrar");
        } else {

            ctlLocal.eliminarLocal(direccion, ciudadEditar);
            JOptionPane.showMessageDialog(null, "se ha editado correctamente");
            listaLocales(codigo);
            limpiarCampos();

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tbLocalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLocalMouseClicked
        // TODO add your handling code here:

        int seleccionar;

        seleccionar = tbLocal.rowAtPoint(evt.getPoint());

        txtNombreNegocio.setText(String.valueOf(tbLocal.getValueAt(seleccionar, 0)));
        txtDireccion.setText(String.valueOf(tbLocal.getValueAt(seleccionar, 1)));
        txtNit.setText(String.valueOf(tbLocal.getValueAt(seleccionar, 2)));
        txtEncargado.setText(String.valueOf(tbLocal.getValueAt(seleccionar, 3)));
        ciudadEditar = String.valueOf(tbLocal.getValueAt(seleccionar, 5));
        direccionActual = String.valueOf(tbLocal.getValueAt(seleccionar, 1));
        
        jcDepartamento.setSelectedItem(String.valueOf(tbLocal.getValueAt(seleccionar, 4)));
        jcCiudad.setSelectedItem(String.valueOf(tbLocal.getValueAt(seleccionar, 5)));
    }//GEN-LAST:event_tbLocalMouseClicked

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        
        char enter = evt.getKeyChar();

        if (enter == KeyEvent.VK_ENTER) {

            btnBuscarCliente.doClick();

        }
    }//GEN-LAST:event_txtCodigoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcCiudad;
    private javax.swing.JComboBox<String> jcDepartamento;
    private javax.swing.JTable tbLocal;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEncargado;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreNegocio;
    private javax.swing.JTextField txtTipoCliente;
    // End of variables declaration//GEN-END:variables
}
