/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CtlUsuario;
import Modelo.Usuario;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALAN
 */
public class FrmListaUsario extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmListaUsario
     */
    CtlUsuario ctlUsuario;
    public String usuario;

    public FrmListaUsario() {
        initComponents();
        this.setSize(new Dimension(700, 450));
        this.setTitle("Lista Usuarios");
        cargarCombo();
        ctlUsuario = new CtlUsuario();
        Inicio usuarioInicio = new Inicio();
        usuario = usuarioInicio.usuarioIniciado;
        boolean estado = verificar(usuario);
        botonesInabilitar(estado);
        listar(estado);

    }

    public void cargarCombo() {
        cbFiltro.removeAllItems();
        cbFiltro.addItem("Seleccione");
        cbFiltro.addItem("nombre_Usuario");
        cbFiltro.addItem("tipo_Usuario");
        cbFiltro.addItem("estado");
        cbFiltro.addItem("nombre");
        cbFiltro.addItem("apellido");
    }

    public void listar(boolean estado) {

        if (estado == true) {

            ArrayList<Usuario> usu = ctlUsuario.listarUsuario();

            DefaultTableModel modelo = (DefaultTableModel) tbListaUsuario.getModel();
            modelo.setRowCount(0);

            for (Usuario usuario1 : usu) {

                modelo.addRow(new Object[]{usuario1.getNombre_Usuario(), usuario1.getPw(),
                    usuario1.getTipo_Usuario(), usuario1.getEstado(), usuario1.getNombre(), usuario1.getApellido()});

            }
        }

    }

    public void botonesInabilitar(boolean estado) {

        btnFiltrar.setEnabled(estado);

    }

    public Boolean verificar(String usuario) {

        Usuario usu = ctlUsuario.tipoUsuario(usuario);

        if (usu.getTipo_Usuario().equals("Empleado")) {

            JOptionPane.showMessageDialog(null, "usted no es administrador");
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        cbFiltro = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListaUsuario = new javax.swing.JTable();
        btnFiltrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Lista de Usuarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Columna");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));
        getContentPane().add(txtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 150, -1));

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Dato");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 73, -1, -1));

        tbListaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre_Usuario", "Contraseña", "Tipo Usuario", "Estado", "Nombre", "Apellido"
            }
        ));
        jScrollPane1.setViewportView(tbListaUsuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 650, 280));

        btnFiltrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:

        String dato, columna;

        dato = txtFiltro.getText();
        columna = (String) cbFiltro.getSelectedItem();

        if (dato.isEmpty() || columna.equals("Seleccione")) {

            JOptionPane.showMessageDialog(null, "por favor seleccione una columna y digite el dato");

        } else {

            try {

                ArrayList<Usuario> listausuario = ctlUsuario.filtarUsuario(columna, dato);

                DefaultTableModel modelo = (DefaultTableModel) tbListaUsuario.getModel();
                modelo.setRowCount(0);

                for (Usuario usuario1 : listausuario) {

                    modelo.addRow(new Object[]{usuario1.getNombre_Usuario(), usuario1.getPw(),
                        usuario1.getTipo_Usuario(), usuario1.getEstado(), usuario1.getNombre(), usuario1.getApellido()});

                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }//GEN-LAST:event_btnFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> cbFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbListaUsuario;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
