/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CtlAgenda;
import DTO.DtoAgenda;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class FrmListaAgenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmListaAgenda
     */
    CtlAgenda ctlAgenda;

    public FrmListaAgenda() {
        initComponents();
        this.setSize(new Dimension(1250, 650));
        this.setTitle("Lista Agenda");
        ctlAgenda = new CtlAgenda();
        listar();

    }

    public void listar() {

        ArrayList<DtoAgenda> lista = ctlAgenda.listarAgenda();

        DefaultTableModel modelo = (DefaultTableModel) tbAgenda.getModel();
        modelo.setRowCount(0);

        for (DtoAgenda dtoAgenda : lista) {

            modelo.addRow(new Object[]{dtoAgenda.getsNroFactura(), dtoAgenda.getlNombreNegocio(),
                dtoAgenda.getlDireccion(), dtoAgenda.getcCelular(), dtoAgenda.getCiNombre(),
                dtoAgenda.getMuNombre(), dtoAgenda.getaFecha(), dtoAgenda.getaHora(),
                dtoAgenda.getaConfirmacion(), dtoAgenda.getaObservacion(), dtoAgenda.getsTecnico()});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcFecha = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAgenda = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Lista Agenda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Fecha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        jcFecha.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 150, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 68, -1, -1));

        tbAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nro Factura", "Nombre Negocio", "Direccion", "Telefono", "Ciudad", "Departamento", "Fecha", "Hora", "Confirmacion", "Observacion", "Tecnico"
            }
        ));
        jScrollPane1.setViewportView(tbAgenda);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1200, 490));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Exportar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();

        if (fecha.isEmpty()) {

            JOptionPane.showMessageDialog(null, "por favor seleccione una fecha");

        } else {

            ArrayList<DtoAgenda> lista = ctlAgenda.listarAgendaPorFiltro(fecha);

            DefaultTableModel modelo = (DefaultTableModel) tbAgenda.getModel();
            modelo.setRowCount(0);

            for (DtoAgenda dtoAgenda : lista) {

                modelo.addRow(new Object[]{dtoAgenda.getsNroFactura(), dtoAgenda.getlNombreNegocio(),
                    dtoAgenda.getlDireccion(), dtoAgenda.getcCelular(), 
                    dtoAgenda.getCiNombre(), dtoAgenda.getMuNombre(),
                    dtoAgenda.getaFecha(), dtoAgenda.getaHora(),
                    dtoAgenda.getaConfirmacion(), dtoAgenda.getaObservacion(), dtoAgenda.getsTecnico()});

            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();

        if (fecha.isEmpty()) {

            JOptionPane.showMessageDialog(null, "porfavor llene los datos");

        } else {

            try {

                ctlAgenda.reporteAgenda(fecha);
                JOptionPane.showMessageDialog(null, "Agenda generada");

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e.getMessage());

            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jcFecha;
    private javax.swing.JTable tbAgenda;
    // End of variables declaration//GEN-END:variables
}
