/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CtlProspectoCliente;
import DTO.DtoProspectoCliente;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class FrmListaProspectoCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmListaProspectoCliente
     */
    CtlProspectoCliente ctlProspectoCliente;

    public FrmListaProspectoCliente() {
        initComponents();
        ctlProspectoCliente = new CtlProspectoCliente();
        this.setSize(new Dimension(1450, 600));
        this.setTitle("Lista Prospectos de Clientes");
        inHabilitar();
        lista();

    }

    public void inHabilitar() {

        jcFecha.setEnabled(false);
    }

    public void lista() {

        ArrayList<DtoProspectoCliente> lista = ctlProspectoCliente.listarProspectoCliente();

        DefaultTableModel modelo = (DefaultTableModel) tbProspectoCliente.getModel();
        modelo.setRowCount(0);

        for (DtoProspectoCliente dtoProspectoCliente : lista) {

            modelo.addRow(new Object[]{dtoProspectoCliente.getEstado(),
                dtoProspectoCliente.getFecha(), dtoProspectoCliente.getTipo(),
                dtoProspectoCliente.getNombre(), dtoProspectoCliente.getApellido(),
                dtoProspectoCliente.getCelular(), dtoProspectoCliente.getCorreo(),
                dtoProspectoCliente.getNombreNegocio(), dtoProspectoCliente.getDireccion(),
                dtoProspectoCliente.getNit(), dtoProspectoCliente.getEncargado(),
                dtoProspectoCliente.getVendedor(), dtoProspectoCliente.getServicioOfrecido(),
                dtoProspectoCliente.getValor(), dtoProspectoCliente.getMunicipio(),
                dtoProspectoCliente.getCiudad()});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        cbColumna = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProspectoCliente = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jcFecha = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Lista de Prospecto de Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Columna");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));
        getContentPane().add(txtDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 150, -1));

        cbColumna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Estado", "Fecha", "Tipo", "Nombre", "Apellido", "Celular", "Correo", "Nombre del Negocio", "Direccion", "Nit" }));
        cbColumna.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbColumnaItemStateChanged(evt);
            }
        });
        getContentPane().add(cbColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Dato");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 73, -1, -1));

        tbProspectoCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Estado", "Fecha", "Tipo", "Nombre", "Apellido", "Celular", "Correo", "Nombre del Negocio", "Direccion", "Nit", "Encargado", "Vendedor", "Servicio Ofrecido", "Valor", "Departamento", "Ciudad"
            }
        ));
        jScrollPane1.setViewportView(tbProspectoCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1410, 440));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 73, -1, -1));

        jcFecha.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 150, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbColumnaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbColumnaItemStateChanged
        // TODO add your handling code here:

        String datoSeleccionado;

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            datoSeleccionado = (String) evt.getItem();

            if (datoSeleccionado.equals("Fecha")) {

                jcFecha.setEnabled(true);
                txtDato.setEnabled(false);

            } else {

                txtDato.setEnabled(true);
                jcFecha.setEnabled(false);

            }
        }
    }//GEN-LAST:event_cbColumnaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String dato, columna;

        columna = (String) cbColumna.getSelectedItem();
        dato = txtDato.getText();

        if (columna.equals("Seleccione")) {

            JOptionPane.showMessageDialog(null, "por favor selecione una columna y "
                    + "digite el dato para filtar");

        } else {

            try {

                if (columna.equals("Fecha")) {

                    String fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();
                    ArrayList<DtoProspectoCliente> lista = ctlProspectoCliente.listarPorFiltro(columna, fecha);

                    DefaultTableModel modelo = (DefaultTableModel) tbProspectoCliente.getModel();
                    modelo.setRowCount(0);

                    for (DtoProspectoCliente dtoProspectoCliente : lista) {

                        modelo.addRow(new Object[]{dtoProspectoCliente.getEstado(),
                            dtoProspectoCliente.getFecha(), dtoProspectoCliente.getTipo(),
                            dtoProspectoCliente.getNombre(), dtoProspectoCliente.getApellido(),
                            dtoProspectoCliente.getCelular(), dtoProspectoCliente.getCorreo(),
                            dtoProspectoCliente.getNombreNegocio(), dtoProspectoCliente.getDireccion(),
                            dtoProspectoCliente.getNit(), dtoProspectoCliente.getEncargado(),
                            dtoProspectoCliente.getVendedor(), dtoProspectoCliente.getServicioOfrecido(), 
                            dtoProspectoCliente.getValor(), dtoProspectoCliente.getMunicipio(), 
                            dtoProspectoCliente.getCiudad()});

                    }

                } else {

                    ArrayList<DtoProspectoCliente> lista = ctlProspectoCliente.listarPorFiltro(columna, dato);

                    DefaultTableModel modelo = (DefaultTableModel) tbProspectoCliente.getModel();
                    modelo.setRowCount(0);

                    for (DtoProspectoCliente dtoProspectoCliente : lista) {

                        modelo.addRow(new Object[]{dtoProspectoCliente.getEstado(),
                            dtoProspectoCliente.getFecha(), dtoProspectoCliente.getTipo(),
                            dtoProspectoCliente.getNombre(), dtoProspectoCliente.getApellido(),
                            dtoProspectoCliente.getCelular(), dtoProspectoCliente.getCorreo(),
                            dtoProspectoCliente.getNombreNegocio(), dtoProspectoCliente.getDireccion(),
                            dtoProspectoCliente.getNit(), dtoProspectoCliente.getEncargado(),
                            dtoProspectoCliente.getVendedor(), dtoProspectoCliente.getServicioOfrecido(),
                            dtoProspectoCliente.getValor(), dtoProspectoCliente.getMunicipio(),
                            dtoProspectoCliente.getCiudad()});

                    }

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbColumna;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jcFecha;
    private javax.swing.JTable tbProspectoCliente;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
