/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CtlServicio;
import Controlador.CtlUsuario;
import DTO.DtoServicio;
import Modelo.Usuario;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class FrmListaServicios extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmListaServicios
     */
    CtlServicio ctlServicio;
    CtlUsuario ctlUsuario;
    public String usuarioIniciado;
    String vendedor;

    public FrmListaServicios() {
        initComponents();
        this.setSize(new Dimension(1500, 650));
        this.setTitle("Lista Servicios");
        ctlServicio = new CtlServicio();
        ctlUsuario = new CtlUsuario();
        Inicio usuarioInicio = new Inicio();
        usuarioIniciado = usuarioInicio.usuarioIniciado;
        buscarVendedor();
        listar();
        inHabilitar();

    }

    public void buscarVendedor() {

        Usuario usuario = ctlUsuario.buscarUsuario(usuarioIniciado);
        vendedor = usuario.getNombre();

    }

    public void inHabilitar() {

        jcFecha.setEnabled(false);
        jcFechaAgendamiento.setEnabled(false);
    }

    public void listar() {

        ArrayList<DtoServicio> lista = ctlServicio.listarServicios1();

        DefaultTableModel modelo = (DefaultTableModel) tbServicios.getModel();
        modelo.setRowCount(0);

        for (DtoServicio dtoServicio : lista) {

            modelo.addRow(new Object[]{dtoServicio.getNroFactura(),
                dtoServicio.getNombre(), dtoServicio.getNombreNegocio(),
                dtoServicio.getDireccion(), dtoServicio.getTipoServicio(),
                dtoServicio.getRefuerzo(), dtoServicio.getTecnico(),
                dtoServicio.getFecha(), dtoServicio.getPeriocidad(),
                dtoServicio.getProxFecha(), dtoServicio.getPago(), dtoServicio.getValor(),
                dtoServicio.getVendedor(), dtoServicio.getObservacion(),
                dtoServicio.getAfecha(), dtoServicio.getAhora(), dtoServicio.getAconfirmacion()});

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbColumna = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbServicios = new javax.swing.JTable();
        btnFiltrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcFecha = new com.toedter.calendar.JDateChooser();
        jcFechaAgendamiento = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Columna");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Lista Servicios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        cbColumna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Nombre del Cliente", "Nombre del Negocio", "Direccion", "Nro Factura", "TipoServicio", "Tecnico", "Fecha", "Periocidad", "Proxima Fecha", "Pago", "Vendedor y Fecha", "Observacion", "Fecha Agenda" }));
        cbColumna.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbColumnaItemStateChanged(evt);
            }
        });
        getContentPane().add(cbColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Dato");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 73, -1, -1));

        txtDato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatoKeyTyped(evt);
            }
        });
        getContentPane().add(txtDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 190, -1));

        tbServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nro Servicio", "Nombre del Cliente", "Nombre del Negocio", "Direccion", "Tipo de Servicio", "Refuerzo", "Tecnico", "Fecha", "Periocidad", "Proxima Fecha", "Pago", "Valor", "Vendedor", "Observacion", "Fecha Agenda", "Hora", "Confirmacion"
            }
        ));
        tbServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbServiciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbServicios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1460, 480));

        btnFiltrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 73, -1, -1));

        jcFecha.setDateFormatString("yyyy-MM");
        getContentPane().add(jcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 150, -1));

        jcFechaAgendamiento.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jcFechaAgendamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 70, 150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Fecha Agendamiento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 73, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:

        String columna, dato;

        columna = (String) cbColumna.getSelectedItem();
        dato = txtDato.getText();

        if (columna.equals("Seleccione")) {

            JOptionPane.showMessageDialog(null, "por favor selecione una columna y "
                    + "digite el dato para filtar");

        } else {

            try {

                if (columna.equals("Vendedor y Fecha")) {

                    String fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();
                    ArrayList<DtoServicio> lista = ctlServicio.listarServiciosPorFiltroVendedor(fecha, vendedor);

                    DefaultTableModel modelo = (DefaultTableModel) tbServicios.getModel();
                    modelo.setRowCount(0);

                    for (DtoServicio dtoServicio : lista) {

                        modelo.addRow(new Object[]{dtoServicio.getNroFactura(),
                            dtoServicio.getNombre(), dtoServicio.getNombreNegocio(),
                            dtoServicio.getDireccion(), dtoServicio.getTipoServicio(),
                            dtoServicio.getRefuerzo(), dtoServicio.getTecnico(),
                            dtoServicio.getFecha(), dtoServicio.getPeriocidad(),
                            dtoServicio.getProxFecha(), dtoServicio.getPago(), dtoServicio.getValor(),
                            dtoServicio.getVendedor(), dtoServicio.getObservacion(),
                            dtoServicio.getAfecha(), dtoServicio.getAhora(), dtoServicio.getAconfirmacion()});

                    }

                } else if (columna.equals("Fecha")) {

                    String fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();
                    ArrayList<DtoServicio> lista = ctlServicio.listarServiciosPorFiltro(columna, fecha);

                    DefaultTableModel modelo = (DefaultTableModel) tbServicios.getModel();
                    modelo.setRowCount(0);

                    for (DtoServicio dtoServicio : lista) {

                        modelo.addRow(new Object[]{dtoServicio.getNroFactura(),
                            dtoServicio.getNombre(), dtoServicio.getNombreNegocio(),
                            dtoServicio.getDireccion(), dtoServicio.getTipoServicio(),
                            dtoServicio.getRefuerzo(), dtoServicio.getTecnico(),
                            dtoServicio.getFecha(), dtoServicio.getPeriocidad(),
                            dtoServicio.getProxFecha(), dtoServicio.getPago(), dtoServicio.getValor(),
                            dtoServicio.getVendedor(), dtoServicio.getObservacion(),
                            dtoServicio.getAfecha(), dtoServicio.getAhora(), dtoServicio.getAconfirmacion()});

                    }

                } else if (columna.equals("Fecha Agenda")) {

                    String fecha = ((JTextField) jcFechaAgendamiento.getDateEditor().getUiComponent()).getText();
                    ArrayList<DtoServicio> lista = ctlServicio.listarServiciosPorFiltro(columna, fecha);

                    DefaultTableModel modelo = (DefaultTableModel) tbServicios.getModel();
                    modelo.setRowCount(0);

                    for (DtoServicio dtoServicio : lista) {

                        modelo.addRow(new Object[]{dtoServicio.getNroFactura(),
                            dtoServicio.getNombre(), dtoServicio.getNombreNegocio(),
                            dtoServicio.getDireccion(), dtoServicio.getTipoServicio(),
                            dtoServicio.getRefuerzo(), dtoServicio.getTecnico(),
                            dtoServicio.getFecha(), dtoServicio.getPeriocidad(),
                            dtoServicio.getProxFecha(), dtoServicio.getPago(), dtoServicio.getValor(),
                            dtoServicio.getVendedor(), dtoServicio.getObservacion(),
                            dtoServicio.getAfecha(), dtoServicio.getAhora(), dtoServicio.getAconfirmacion()});

                    }

                } else {

                    ArrayList<DtoServicio> lista = ctlServicio.listarServiciosPorFiltro(columna, dato);

                    DefaultTableModel modelo = (DefaultTableModel) tbServicios.getModel();
                    modelo.setRowCount(0);

                    for (DtoServicio dtoServicio : lista) {

                        modelo.addRow(new Object[]{dtoServicio.getNroFactura(),
                            dtoServicio.getNombre(), dtoServicio.getNombreNegocio(),
                            dtoServicio.getDireccion(), dtoServicio.getTipoServicio(),
                            dtoServicio.getRefuerzo(), dtoServicio.getTecnico(),
                            dtoServicio.getFecha(), dtoServicio.getPeriocidad(),
                            dtoServicio.getProxFecha(), dtoServicio.getPago(), dtoServicio.getValor(),
                            dtoServicio.getVendedor(), dtoServicio.getObservacion(),
                            dtoServicio.getAfecha(), dtoServicio.getAhora(), dtoServicio.getAconfirmacion()});

                    }

                }

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }

    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void txtDatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoKeyTyped
        // TODO add your handling code here:

        char enter = evt.getKeyChar();

        if (enter == KeyEvent.VK_ENTER) {

            btnFiltrar.doClick();

        }
    }//GEN-LAST:event_txtDatoKeyTyped

    private void tbServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbServiciosMouseClicked
        // TODO add your handling code here:

        String factura, direccion;
        int seleccionar;

        seleccionar = tbServicios.rowAtPoint(evt.getPoint());

        factura = String.valueOf(tbServicios.getValueAt(seleccionar, 0));

        ctlServicio.almacenarDatos1(factura);

        DetalleServicio informe = new DetalleServicio();
        informe.setVisible(true);
    }//GEN-LAST:event_tbServiciosMouseClicked

    private void cbColumnaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbColumnaItemStateChanged
        // TODO add your handling code here:

        String datoSeleccionado;

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            datoSeleccionado = (String) evt.getItem();

            if (datoSeleccionado.equals("Vendedor y Fecha")) {

                jcFecha.setEnabled(true);
                txtDato.setEnabled(false);
                jcFechaAgendamiento.setEnabled(false);

            } else if (datoSeleccionado.equals("Fecha")) {

                jcFecha.setEnabled(true);
                txtDato.setEnabled(false);
                jcFechaAgendamiento.setEnabled(false);

            } else if (datoSeleccionado.equals("Fecha Agenda")) {

                jcFechaAgendamiento.setEnabled(true);
                txtDato.setEnabled(false);
                jcFecha.setEnabled(false);

            } else {

                txtDato.setEnabled(true);
                jcFecha.setEnabled(false);
                jcFechaAgendamiento.setEnabled(false);

            }
        }
    }//GEN-LAST:event_cbColumnaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> cbColumna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jcFecha;
    private com.toedter.calendar.JDateChooser jcFechaAgendamiento;
    private javax.swing.JTable tbServicios;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
