/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CtlLocal;
import Controlador.CtlServicio;
import DTO.DtoClienteLocal;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALAN
 */
public class FrmListaClienteLocal extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmListarClienteLocal
     */
    CtlLocal ctlLocal;
    CtlServicio ctlServicio;

    public FrmListaClienteLocal() {
        initComponents();
        this.setSize(new Dimension(1360, 650));
        this.setTitle("Lista Locales");
        ctlLocal = new CtlLocal();
        ctlServicio = new CtlServicio();
        listar();
    }

    public void listar() {

        ArrayList<DtoClienteLocal> lista = ctlLocal.listaClienteLocal();

        DefaultTableModel modelo = (DefaultTableModel) tbLocal.getModel();
        modelo.setRowCount(0);

        for (DtoClienteLocal dtoClienteLocal : lista) {

            modelo.addRow(new Object[]{dtoClienteLocal.getCodigo(), dtoClienteLocal.getTipo(),
                dtoClienteLocal.getNombre(), dtoClienteLocal.getApellido(),
                dtoClienteLocal.getCelular(), dtoClienteLocal.getCorreo(),
                dtoClienteLocal.getNombreNegocio(), dtoClienteLocal.getDireccion(),
                dtoClienteLocal.getNit(), dtoClienteLocal.getEncargado(), dtoClienteLocal.getMunicipio(),
                dtoClienteLocal.getCiudad()});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcColumna = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        BtnFiltrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLocal = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Lista Locales");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Columna");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        jcColumna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Codigo", "Tipo", "Nombre", "Apellido", "Nombre de Negocio", "Direccion", "Nit", "Encargado", "Departamento", "Ciudad" }));
        getContentPane().add(jcColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Dato");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 73, -1, -1));

        txtDato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatoKeyTyped(evt);
            }
        });
        getContentPane().add(txtDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 150, -1));

        BtnFiltrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnFiltrar.setText("Filtrar");
        BtnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 67, -1, -1));

        tbLocal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Tipo", "Nombre", "Apellido", "Celular", "Correo", "Nombre del negocio", "Direccion", "Nit", "Encargado", "Departamento", "Ciudad"
            }
        ));
        tbLocal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLocalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbLocal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 123, 1320, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoKeyTyped
        // TODO add your handling code here:

        char enter = evt.getKeyChar();

        if (enter == KeyEvent.VK_ENTER) {

            BtnFiltrar.doClick();

        }
    }//GEN-LAST:event_txtDatoKeyTyped

    private void BtnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFiltrarActionPerformed
        // TODO add your handling code here:

        String columna, dato;

        columna = (String) jcColumna.getSelectedItem();
        dato = txtDato.getText();

        if (columna.equals("Seleccione") || dato.isEmpty()) {

            JOptionPane.showMessageDialog(null, "seleccione una columna y llene el campo dato");

        } else {

            ArrayList<DtoClienteLocal> lista = ctlLocal.listaClienteLocalporFiltro(columna, dato);

            DefaultTableModel modelo = (DefaultTableModel) tbLocal.getModel();
            modelo.setRowCount(0);

            for (DtoClienteLocal dtoClienteLocal : lista) {

                modelo.addRow(new Object[]{dtoClienteLocal.getCodigo(), dtoClienteLocal.getTipo(),
                    dtoClienteLocal.getNombre(), dtoClienteLocal.getApellido(),
                    dtoClienteLocal.getCelular(), dtoClienteLocal.getCorreo(),
                    dtoClienteLocal.getNombreNegocio(), dtoClienteLocal.getDireccion(),
                    dtoClienteLocal.getNit(), dtoClienteLocal.getEncargado(), dtoClienteLocal.getMunicipio(),
                    dtoClienteLocal.getCiudad()});

            }

        }
    }//GEN-LAST:event_BtnFiltrarActionPerformed

    private void tbLocalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLocalMouseClicked
        // TODO add your handling code here:
       
        String codigo, direccion;
        int seleccionar;

        seleccionar = tbLocal.rowAtPoint(evt.getPoint());
        
        codigo = String.valueOf(tbLocal.getValueAt(seleccionar, 0));
        direccion = String.valueOf(tbLocal.getValueAt(seleccionar, 7));
        
        ctlServicio.almacenarDatos(codigo, direccion);
        
        DetalleCliente informe = new DetalleCliente();
        informe.setVisible(true);
        
    }//GEN-LAST:event_tbLocalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFiltrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcColumna;
    private javax.swing.JTable tbLocal;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
