/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CtlCliente;
import Controlador.CtlLocal;
import Controlador.CtlProspectoCliente;
import Controlador.CtlUsuario;
import DTO.DtoProspectoCliente;
import Modelo.Ciudad;
import Modelo.Cliente;
import Modelo.Local;
import Modelo.Miles;
import Modelo.Municipio;
import Modelo.ProspectoCliente;
import Modelo.Usuario;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class FrmProspectoCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProspectoCliente
     */
    CtlLocal ctlLocal;
    CtlProspectoCliente ctlProspectoCliente;
    CtlCliente ctlCliente;
    CtlUsuario ctlUsuario;
    public String usuarioIniciado;
    String vendedor, direccionAnterior;

    public FrmProspectoCliente() throws ParseException {
        initComponents();
        this.setSize(new Dimension(1050, 680));
        this.setTitle("Prospectos de Clientes");
        ctlLocal = new CtlLocal();
        ctlProspectoCliente = new CtlProspectoCliente();
        ctlCliente = new CtlCliente();
        ctlCliente = new CtlCliente();
        ctlUsuario = new CtlUsuario();
        Inicio usuarioInicio = new Inicio();
        usuarioIniciado = usuarioInicio.usuarioIniciado;
        buscarVendedor();
        llenarComboMunicipio();
        fechaHoy();
    }

    public void buscarVendedor() {

        Usuario usuario = ctlUsuario.buscarUsuario(usuarioIniciado);
        vendedor = usuario.getNombre();

    }

    public void llenarComboMunicipio() {

        ArrayList<Municipio> lista = ctlLocal.cargarMunicipio();

        jcDepartamento.removeAllItems();
        jcDepartamento.addItem("Seleccione");

        jcCiudad.removeAllItems();
        jcCiudad.addItem("Seleccione");

        for (Municipio municipio : lista) {

            jcDepartamento.addItem(municipio.getNombre());

        }

    }

    public void fechaHoy() throws ParseException {

        Date fecha;
        String hoy1;

        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        LocalDate hoy = LocalDate.now();
        hoy1 = hoy + "";
        fecha = format.parse(hoy1);

        jcFecha.setDate(fecha);

        ArrayList<DtoProspectoCliente> lista = ctlProspectoCliente.listaProspectoCliente(hoy1);

        DefaultTableModel modelo = (DefaultTableModel) tbProspectoCliente.getModel();
        modelo.setRowCount(0);

        for (DtoProspectoCliente dtoProspectoCliente : lista) {

            modelo.addRow(new Object[]{dtoProspectoCliente.getEstado(),
                dtoProspectoCliente.getFecha(), dtoProspectoCliente.getTipo(),
                dtoProspectoCliente.getNombre(), dtoProspectoCliente.getApellido(),
                dtoProspectoCliente.getCelular(), dtoProspectoCliente.getCorreo(),
                dtoProspectoCliente.getNombreNegocio(), dtoProspectoCliente.getDireccion()});

        }
    }

    public void vaciarCampos() {

        txtApellidoCliente.setText("");
        txtCelularCliente.setText("");
        txtCorreoCliente.setText("");
        txtDireccionNegocio.setText("");
        txtEncargardoNegocio.setText("");
        txtNitNegocio.setText("");
        txtNombreCliente.setText("");
        txtNombreNegocio.setText("");
        txtServicio.setText("");
        txtValor.setText("");
        cbEstado.setSelectedItem("Seleccione");
        cbTipo.setSelectedItem("Seleccione");
        jcDepartamento.setSelectedItem("Seleccione");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtApellidoCliente = new javax.swing.JTextField();
        txtCelularCliente = new javax.swing.JTextField();
        txtCorreoCliente = new javax.swing.JTextField();
        txtNombreNegocio = new javax.swing.JTextField();
        txtDireccionNegocio = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        txtNitNegocio = new javax.swing.JTextField();
        txtEncargardoNegocio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jcDepartamento = new javax.swing.JComboBox<>();
        jcCiudad = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jcFecha = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProspectoCliente = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Prospecto de Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 223, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 273, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Celular");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 323, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Correo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 373, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Estado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nombre Del Negocio");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 73, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Direccion");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 123, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nit");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 173, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Encargado");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 223, -1, -1));
        getContentPane().add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 150, -1));
        getContentPane().add(txtApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 150, -1));
        getContentPane().add(txtCelularCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 150, -1));
        getContentPane().add(txtCorreoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 150, -1));
        getContentPane().add(txtNombreNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 150, -1));
        getContentPane().add(txtDireccionNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 150, -1));

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Potencial", "Cliente" }));
        getContentPane().add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Tipo");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 173, -1, -1));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Residencial", "Comercial" }));
        getContentPane().add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 150, -1));
        getContentPane().add(txtNitNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 150, -1));
        getContentPane().add(txtEncargardoNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Departamento");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 273, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Ciudad");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 323, -1, -1));

        jcDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcDepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcDepartamentoItemStateChanged(evt);
            }
        });
        getContentPane().add(jcDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 150, -1));

        jcCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcCiudadItemStateChanged(evt);
            }
        });
        getContentPane().add(jcCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 150, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 120, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 120, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Fecha");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 123, -1, -1));

        jcFecha.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 150, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Servicio que se ofrecio");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 373, -1, -1));
        getContentPane().add(txtServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 150, -1));

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorKeyReleased(evt);
            }
        });
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 150, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Valor");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 73, -1, -1));

        tbProspectoCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Estado", "Fecha", "Tipo", "Nombre", "Apellido", "Celular", "Correo", "Nombre del Negocio", "Direccion"
            }
        ));
        tbProspectoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProspectoClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProspectoCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 1010, 220));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Filtrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcCiudadItemStateChanged
        // TODO add your handling code here:


    }//GEN-LAST:event_jcCiudadItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int consecutivo, precio;
        String letra1, numero, codigoCadena = null;

        String estado, fecha, tipo, nombre, apellido, celular, correo, nombreNegocio,
                direccion, nit, encargado, municipio, ciudad, servicioOfrecido, valor;

        estado = (String) cbEstado.getSelectedItem();
        fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();
        tipo = (String) cbTipo.getSelectedItem();
        nombre = txtNombreCliente.getText();
        apellido = txtApellidoCliente.getText();
        celular = txtCelularCliente.getText();
        correo = txtCorreoCliente.getText();
        nombreNegocio = txtNombreNegocio.getText();
        direccion = txtDireccionNegocio.getText();
        nit = txtNitNegocio.getText();
        encargado = txtEncargardoNegocio.getText();
        municipio = (String) jcDepartamento.getSelectedItem();
        ciudad = (String) jcCiudad.getSelectedItem();
        servicioOfrecido = txtServicio.getText();
        valor = txtValor.getText();

        if (estado.equals("Seleccione") || fecha.isEmpty() || tipo.equals("Seleccione")
                || nombre.isEmpty() || apellido.isEmpty() || celular.isEmpty() || correo.isEmpty()
                || nombreNegocio.isEmpty() || direccion.isEmpty() || nit.isEmpty() || encargado.isEmpty()
                || municipio.equals("Seleccione") || ciudad.equals("Seleccione")) {

            JOptionPane.showMessageDialog(null, "Llene los campos y selecione");

        } else {

            try {

                if (estado.equals("Cliente")) {

                    String num = valor.replace(".", "");
                    precio = Integer.parseInt(num);
                    ProspectoCliente pc = new ProspectoCliente(0, 0,
                            precio, estado, fecha, tipo, nombre, apellido, celular, correo, nombreNegocio,
                            direccion, nit, encargado, servicioOfrecido, vendedor);

                    Cliente cliente = ctlCliente.buscarUltimoRegistroCliente();

                    String[] separarTodo = cliente.getCodigo().split("C");

                    if (separarTodo.length > 1) {

                        letra1 = separarTodo[0];
                        numero = separarTodo[1];

                        consecutivo = Integer.parseInt(numero) + 1;

                        codigoCadena = "C" + consecutivo;

                    } else {

                        System.out.println("nada");

                    }

                    Cliente nuevoCliente = new Cliente(0, codigoCadena,
                            tipo, nombre, apellido, celular, correo);
                    ctlCliente.guardarCliente(nuevoCliente);

                    Local l = new Local(0, 0, 0, nombreNegocio, direccion, nit, encargado);
                    ctlLocal.guardarLocal(l, ciudad, nuevoCliente.getCodigo());

                    ctlProspectoCliente.editarProspectoCliente(pc, ciudad, direccionAnterior);
                    JOptionPane.showMessageDialog(null, "Se ha editado Correctamente");
                    vaciarCampos();
                    fechaHoy();

                } else {

                    String num = valor.replace(".", "");
                    precio = Integer.parseInt(num);
                    ProspectoCliente pc = new ProspectoCliente(0, 0,
                            precio, estado, fecha, tipo, nombre, apellido, celular, correo, nombreNegocio,
                            direccion, nit, encargado, servicioOfrecido, vendedor);

                    ctlProspectoCliente.editarProspectoCliente(pc, ciudad, direccionAnterior);
                    JOptionPane.showMessageDialog(null, "Se ha editado Correctamente");
                    vaciarCampos();
                    fechaHoy();

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jcDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcDepartamentoItemStateChanged
        // TODO add your handling code here:

        String datoSeleccionado;

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            datoSeleccionado = (String) evt.getItem();

            if (datoSeleccionado.equals("Seleccione")) {

            } else {

                jcCiudad.removeAllItems();
                jcCiudad.addItem("Seleccione");

                ArrayList<Ciudad> lista = ctlLocal.cargarCiudad(datoSeleccionado);

                for (Ciudad ciudad : lista) {

                    jcCiudad.addItem(ciudad.getNombre());

                }

            }
        }
    }//GEN-LAST:event_jcDepartamentoItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int precio;
        String estado, fecha, tipo, nombre, apellido, celular, correo, nombreNegocio,
                direccion, nit, encargado, municipio, ciudad, servicioOfrecido, valor;

        estado = (String) cbEstado.getSelectedItem();
        fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();
        tipo = (String) cbTipo.getSelectedItem();
        nombre = txtNombreCliente.getText();
        apellido = txtApellidoCliente.getText();
        celular = txtCelularCliente.getText();
        correo = txtCorreoCliente.getText();
        nombreNegocio = txtNombreNegocio.getText();
        direccion = txtDireccionNegocio.getText();
        nit = txtNitNegocio.getText();
        encargado = txtEncargardoNegocio.getText();
        municipio = (String) jcDepartamento.getSelectedItem();
        ciudad = (String) jcCiudad.getSelectedItem();
        servicioOfrecido = txtServicio.getText();
        valor = txtValor.getText();

        if (estado.equals("Seleccione") || fecha.isEmpty() || tipo.equals("Seleccione")
                || nombre.isEmpty() || apellido.isEmpty() || celular.isEmpty() || correo.isEmpty()
                || nombreNegocio.isEmpty() || direccion.isEmpty() || nit.isEmpty() || encargado.isEmpty()
                || municipio.equals("Seleccione") || ciudad.equals("Seleccione")
                || servicioOfrecido.isEmpty() || valor.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Llene los campos y selecione");

        } else {

            try {

                String num = valor.replace(".", "");
                precio = Integer.parseInt(num);

                String nombreLimpio = nombreNegocio.stripTrailing();

                ProspectoCliente pc = new ProspectoCliente(0, 0,
                        precio, estado, fecha, tipo, nombre, apellido, celular, correo, nombreLimpio,
                        direccion, nit, encargado, servicioOfrecido, vendedor);

                ctlProspectoCliente.guardarProspectoCliente(pc, ciudad);
                JOptionPane.showMessageDialog(null, "Se ha guardado Correctamente");
                vaciarCampos();
                fechaHoy();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        String direccion;

        direccion = txtDireccionNegocio.getText();

        if (direccion.isEmpty()) {

            JOptionPane.showMessageDialog(null, "elimine por direccion");

        } else {

            try {

                ctlProspectoCliente.eliminarProspectoCliente(direccion);
                JOptionPane.showMessageDialog(null, "se ha eliminado correctamente");
                vaciarCampos();
                fechaHoy();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyReleased
        // TODO add your handling code here:

        Miles op = new Miles();

        if (!txtValor.getText().isEmpty()) {

            double numero;
            String num = txtValor.getText();
            String numeracion = num.replace(".", "");
            numero = Double.parseDouble(numeracion);
            txtValor.setText(op.separarMiles(numero));

        } else {
            txtValor.setText("");
        }
    }//GEN-LAST:event_txtValorKeyReleased

    private void tbProspectoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProspectoClienteMouseClicked
        // TODO add your handling code here:

        int seleccionar, valor1;
        String nombreBuscar, valor;

        seleccionar = tbProspectoCliente.rowAtPoint(evt.getPoint());

        nombreBuscar = String.valueOf(tbProspectoCliente.getValueAt(seleccionar, 8));

        try {

            Miles miles = new Miles();
            DtoProspectoCliente cliente = ctlProspectoCliente.buscarProspectoCliente(nombreBuscar);

            txtApellidoCliente.setText(cliente.getApellido());
            txtCelularCliente.setText(cliente.getCelular());
            txtCorreoCliente.setText(cliente.getCorreo());
            txtDireccionNegocio.setText(cliente.getDireccion());
            txtEncargardoNegocio.setText(cliente.getEncargado());
            txtNitNegocio.setText(cliente.getNit());
            txtNombreCliente.setText(cliente.getNombre());
            txtNombreNegocio.setText(cliente.getNombreNegocio());
            txtServicio.setText(cliente.getServicioOfrecido());

            valor1 = Integer.parseInt(cliente.getValor());
            valor = miles.separarMiles(valor1);
            txtValor.setText(valor);

            cbEstado.setSelectedItem(cliente.getEstado());
            cbTipo.setSelectedItem(cliente.getTipo());

            jcDepartamento.setSelectedItem(cliente.getMunicipio());
            jcCiudad.setSelectedItem(cliente.getCiudad());
            
            direccionAnterior = cliente.getDireccion();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_tbProspectoClienteMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        String fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();
        
        ArrayList<DtoProspectoCliente> lista = ctlProspectoCliente.listaProspectoCliente(fecha);

        DefaultTableModel modelo = (DefaultTableModel) tbProspectoCliente.getModel();
        modelo.setRowCount(0);

        for (DtoProspectoCliente dtoProspectoCliente : lista) {

            modelo.addRow(new Object[]{dtoProspectoCliente.getEstado(),
                dtoProspectoCliente.getFecha(), dtoProspectoCliente.getTipo(),
                dtoProspectoCliente.getNombre(), dtoProspectoCliente.getApellido(),
                dtoProspectoCliente.getCelular(), dtoProspectoCliente.getCorreo(),
                dtoProspectoCliente.getNombreNegocio(), dtoProspectoCliente.getDireccion()});

        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcCiudad;
    private javax.swing.JComboBox<String> jcDepartamento;
    private com.toedter.calendar.JDateChooser jcFecha;
    private javax.swing.JTable tbProspectoCliente;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JTextField txtCelularCliente;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtDireccionNegocio;
    private javax.swing.JTextField txtEncargardoNegocio;
    private javax.swing.JTextField txtNitNegocio;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreNegocio;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
