/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.CtlCliente;
import Controlador.CtlLocal;
import Controlador.CtlProspectoCliente;
import Controlador.CtlUsuario;
import DTO.DtoProspectoCliente;
import Modelo.Ciudad;
import Modelo.Cliente;
import Modelo.Local;
import Modelo.Miles;
import Modelo.Municipio;
import Modelo.ProspectoCliente;
import Modelo.Usuario;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class FrmProspecto extends javax.swing.JFrame {

    /**
     * Creates new form FrmProspecto
     */
    CtlProspectoCliente ctlProspectoCliente;
    CtlCliente ctlCliente;
    CtlLocal ctlLocal;
    CtlUsuario ctlUsuario;
    String vendedor, direccionAnterior, usuarioIniciado;

    public FrmProspecto() throws ParseException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(new Dimension(1000, 450));
        this.setTitle("Prospecto Cliente");
        setIconImage(getIconImage());
        ctlProspectoCliente = new CtlProspectoCliente();
        ctlCliente = new CtlCliente();
        ctlLocal = new CtlLocal();
        ctlUsuario = new CtlUsuario();
        Inicio usuarioInicio = new Inicio();
        usuarioIniciado = usuarioInicio.usuarioIniciado;
        buscarVendedor();
        llenarComboMunicipio();
        llenarCampos();

    }
    
    @Override
    public Image getIconImage() {
        Image retImage = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("IMG/logo.jpg"));
        return retImage;
    }

    public void llenarCampos() throws ParseException {

        int valor1;
        String direccionAlmacenada, ciudadAlmacenada, valor;
        Miles miles = new Miles();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

        direccionAlmacenada = ctlProspectoCliente.direccion;
        ciudadAlmacenada = ctlProspectoCliente.ciudad;

        DtoProspectoCliente dto = ctlProspectoCliente.buscarProspectoCliente(direccionAlmacenada,
                ciudadAlmacenada);

        cbEstado.setSelectedItem(dto.getEstado());
        cbTipo.setSelectedItem(dto.getTipo());
        txtNombreCliente.setText(dto.getNombre());
        txtApellidoCliente.setText(dto.getApellido());
        txtCorreoCliente.setText(dto.getCorreo());
        txtNombreNegocio.setText(dto.getNombreNegocio());
        txtDireccionNegocio.setText(dto.getDireccion());
        txtNitNegocio.setText(dto.getNit());
        txtEncargardoNegocio.setText(dto.getEncargado());
        txtServicio.setText(dto.getServicioOfrecido());
        txtCelularCliente.setText(dto.getCelular());
        txtTelefonoEncargado.setText(dto.getTelefonoEncargado());

        valor1 = Integer.parseInt(dto.getValor());
        valor = miles.separarMiles(valor1);
        txtValor.setText(valor);

        jcFecha.setDate(format.parse(dto.getFecha()));

        direccionAnterior = dto.getDireccion();
        
        jcDepartamento.setSelectedItem(dto.getMunicipio());
        jcCiudad.setSelectedItem(dto.getCiudad());

    }

    public void buscarVendedor() {

        Usuario usuario = ctlUsuario.buscarUsuario(usuarioIniciado);
        vendedor = usuario.getNombre();

    }

    public void llenarComboMunicipio() {

        ArrayList<Municipio> lista = ctlLocal.cargarMunicipio();

        jcDepartamento.removeAllItems();
        jcDepartamento.addItem("Seleccione");

        jcCiudad.removeAllItems();
        jcCiudad.addItem("Seleccione");

        for (Municipio municipio : lista) {

            jcDepartamento.addItem(municipio.getNombre());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jcFecha = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCelularCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCorreoCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNombreNegocio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDireccionNegocio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNitNegocio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEncargardoNegocio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jcDepartamento = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jcCiudad = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtTelefonoEncargado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Prospecto de Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Estado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Potencial", "Cliente" }));
        getContentPane().add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Fecha");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 123, -1, -1));

        jcFecha.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 150, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Tipo");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 173, -1, -1));

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Residencial", "Comercial" }));
        getContentPane().add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 150, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 223, -1, -1));
        getContentPane().add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 273, -1, -1));
        getContentPane().add(txtApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Celular");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 323, -1, -1));
        getContentPane().add(txtCelularCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Correo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 373, -1, -1));
        getContentPane().add(txtCorreoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 150, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Razon Social");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 73, -1, -1));
        getContentPane().add(txtNombreNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Direccion");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 123, -1, -1));
        getContentPane().add(txtDireccionNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 150, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nit");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 173, -1, -1));
        getContentPane().add(txtNitNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 150, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Encargado");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 223, -1, -1));
        getContentPane().add(txtEncargardoNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Departamento");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 323, -1, -1));

        jcDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcDepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcDepartamentoItemStateChanged(evt);
            }
        });
        getContentPane().add(jcDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 150, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Ciudad");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 373, -1, -1));

        jcCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcCiudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcCiudadItemStateChanged(evt);
            }
        });
        getContentPane().add(jcCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 150, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Servicio que se ofrecio");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 73, -1, -1));
        getContentPane().add(txtServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 150, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Valor");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 123, -1, -1));

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorKeyReleased(evt);
            }
        });
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 150, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Telefono Encargado");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 273, -1, -1));
        getContentPane().add(txtTelefonoEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcDepartamentoItemStateChanged
        // TODO add your handling code here:

        String datoSeleccionado;

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            datoSeleccionado = (String) evt.getItem();

            if (datoSeleccionado.equals("Seleccione")) {

            } else {

                jcCiudad.removeAllItems();
                jcCiudad.addItem("Seleccione");

                ArrayList<Ciudad> lista = ctlLocal.cargarCiudad(datoSeleccionado);

                for (Ciudad ciudad : lista) {

                    jcCiudad.addItem(ciudad.getNombre());

                }

            }
        }
    }//GEN-LAST:event_jcDepartamentoItemStateChanged

    private void jcCiudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcCiudadItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jcCiudadItemStateChanged

    private void txtValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyReleased
        // TODO add your handling code here:

        Miles op = new Miles();

        if (!txtValor.getText().isEmpty()) {

            double numero;
            String num = txtValor.getText();
            String numeracion = num.replace(".", "");
            numero = Double.parseDouble(numeracion);
            txtValor.setText(op.separarMiles(numero));

        } else {
            txtValor.setText("");
        }
    }//GEN-LAST:event_txtValorKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int consecutivo, precio;
        String letra1, numero, codigoCadena = null;

        String estado, fecha, tipo, nombre, apellido, celular, correo, nombreNegocio,
        direccion, nit, encargado, municipio, ciudad, servicioOfrecido, valor,
        telefonoEncargado;

        estado = (String) cbEstado.getSelectedItem();
        fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();
        tipo = (String) cbTipo.getSelectedItem();
        nombre = txtNombreCliente.getText();
        apellido = txtApellidoCliente.getText();
        celular = txtCelularCliente.getText();
        correo = txtCorreoCliente.getText();
        nombreNegocio = txtNombreNegocio.getText();
        direccion = txtDireccionNegocio.getText();
        nit = txtNitNegocio.getText();
        encargado = txtEncargardoNegocio.getText();
        municipio = (String) jcDepartamento.getSelectedItem();
        ciudad = (String) jcCiudad.getSelectedItem();
        servicioOfrecido = txtServicio.getText();
        valor = txtValor.getText();
        telefonoEncargado = txtTelefonoEncargado.getText();

        if (estado.equals("Seleccione") || fecha.isEmpty() || tipo.equals("Seleccione")
            || nombre.isEmpty() || apellido.isEmpty() || celular.isEmpty() || correo.isEmpty()
            || nombreNegocio.isEmpty() || direccion.isEmpty() || nit.isEmpty() || encargado.isEmpty()
            || municipio.equals("Seleccione") || ciudad.equals("Seleccione")) {

            JOptionPane.showMessageDialog(null, "Llene los campos y selecione");

        } else {

            try {

                if (estado.equals("Cliente")) {

                    String num = valor.replace(".", "");
                    precio = Integer.parseInt(num);
                    ProspectoCliente pc = new ProspectoCliente(0, 0,
                        precio, estado, fecha, tipo, nombre, apellido, celular, correo, nombreNegocio,
                        direccion, nit, encargado, telefonoEncargado, servicioOfrecido, vendedor);

                    Cliente cliente = ctlCliente.buscarUltimoRegistroCliente();

                    String[] separarTodo = cliente.getCodigo().split("C");

                    if (separarTodo.length > 1) {

                        letra1 = separarTodo[0];
                        numero = separarTodo[1];

                        consecutivo = Integer.parseInt(numero) + 1;

                        codigoCadena = "C" + consecutivo;

                    } else {

                        System.out.println("nada");

                    }

                    Cliente nuevoCliente = new Cliente(0, codigoCadena,
                        tipo, nombre, apellido, celular, correo);
                    ctlCliente.guardarCliente(nuevoCliente);

                    Local l = new Local(0, 0, 0, nombreNegocio, direccion, nit, encargado, 
                            telefonoEncargado, "NA");
                    ctlLocal.guardarLocal(l, ciudad, nuevoCliente.getCodigo());

                    ctlProspectoCliente.editarProspectoCliente(pc, ciudad, direccionAnterior);
                    JOptionPane.showMessageDialog(null, "Se ha editado Correctamente");

                } else {

                    String num = valor.replace(".", "");
                    precio = Integer.parseInt(num);
                    ProspectoCliente pc = new ProspectoCliente(0, 0,
                        precio, estado, fecha, tipo, nombre, apellido, celular, correo, nombreNegocio,
                        direccion, nit, encargado, telefonoEncargado, servicioOfrecido, vendedor);

                    ctlProspectoCliente.editarProspectoCliente(pc, ciudad, direccionAnterior);
                    JOptionPane.showMessageDialog(null, "Se ha editado Correctamente");

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProspecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProspecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProspecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProspecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmProspecto().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(FrmProspecto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jcCiudad;
    private javax.swing.JComboBox<String> jcDepartamento;
    private com.toedter.calendar.JDateChooser jcFecha;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JTextField txtCelularCliente;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtDireccionNegocio;
    private javax.swing.JTextField txtEncargardoNegocio;
    private javax.swing.JTextField txtNitNegocio;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreNegocio;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtTelefonoEncargado;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
