/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CtlLocal;
import Controlador.CtlReportes;
import Controlador.CtlUsuario;
import DTO.DtoServicio;
import Modelo.Ciudad;
import Modelo.Municipio;
import Modelo.Usuario;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class FrmReportes extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmReportes
     */
    CtlLocal ctlLocal;
    CtlReportes ctlReportes;
    CtlUsuario ctlUsuario;
    public String usuarioIniciado;
    String vendedor;

    public FrmReportes() {
        initComponents();
        this.setSize(new Dimension(1620, 650));
        this.setTitle("Reportes");
        ctlLocal = new CtlLocal();
        ctlReportes = new CtlReportes();
        ctlUsuario = new CtlUsuario();
        Inicio usuarioInicio = new Inicio();
        usuarioIniciado = usuarioInicio.usuarioIniciado;
        llenarComboMunicipio();
        inHabilitar();
        buscarVendedor();
    }

    public void llenarComboMunicipio() {

        ArrayList<Municipio> lista = ctlLocal.cargarMunicipio();

        cbDepartamento.removeAllItems();
        cbDepartamento.addItem("Seleccione");

        jcCiudad.removeAllItems();
        jcCiudad.addItem("Seleccione");

        for (Municipio municipio : lista) {

            cbDepartamento.addItem(municipio.getNombre());

        }

    }

    public void inHabilitar() {

        jcCiudad.setEnabled(false);
        cbDepartamento.setEnabled(false);
        txtDato.setEnabled(false);
        jcFecha.setEnabled(false);

    }

    public void buscarVendedor() {

        Usuario usuario = ctlUsuario.buscarUsuario(usuarioIniciado);
        vendedor = usuario.getNombre();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbBusqueda = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbDepartamento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcCiudad = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcFecha = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbReporte = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tipo de Busqueda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        cbBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Departamento", "Ciudad", "Fecha", "Departamento, Ciudad", "Departamento, Ciudad, Fecha", "Vendedor y Fecha", "Pago" }));
        cbBusqueda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbBusquedaItemStateChanged(evt);
            }
        });
        getContentPane().add(cbBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Departamento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 73, -1, -1));

        cbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDepartamentoItemStateChanged(evt);
            }
        });
        getContentPane().add(cbDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Ciudad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 73, -1, -1));

        jcCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 73, -1, -1));

        jcFecha.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 70, 150, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 70, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/excel.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 67, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Reportes");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 15, -1, -1));

        tbReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Tecnico", "Hora", "Tipo de Servicio", "Razon Social", "Nombre", "Apellido", "Direccion", "Telefono", "Nro Servicio", "Pago", "Valor", "Vendedor", "Departamento", "Ciudad"
            }
        ));
        jScrollPane1.setViewportView(tbReporte);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1580, 480));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Dato");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 73, -1, -1));
        getContentPane().add(txtDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDepartamentoItemStateChanged
        // TODO add your handling code here:

        String datoSeleccionado;

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            datoSeleccionado = (String) evt.getItem();

            if (datoSeleccionado.equals("Seleccione")) {

            } else {

                jcCiudad.removeAllItems();
                jcCiudad.addItem("Seleccione");

                ArrayList<Ciudad> lista = ctlLocal.cargarCiudad(datoSeleccionado);

                for (Ciudad ciudad : lista) {

                    jcCiudad.addItem(ciudad.getNombre());

                }

            }
        }

    }//GEN-LAST:event_cbDepartamentoItemStateChanged

    private void cbBusquedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbBusquedaItemStateChanged
        // TODO add your handling code here:

        String datoSeleccionado;

        if (evt.getStateChange() == ItemEvent.SELECTED) {

            datoSeleccionado = (String) evt.getItem();

            if (datoSeleccionado.equals("Vendedor y Fecha")) {

                jcFecha.setEnabled(true);
                txtDato.setEnabled(false);
                jcCiudad.setEnabled(false);
                cbDepartamento.setEnabled(false);

            } else if (datoSeleccionado.equals("Departamento, Ciudad")) {

                jcFecha.setEnabled(false);
                txtDato.setEnabled(false);
                jcCiudad.setEnabled(true);
                cbDepartamento.setEnabled(true);

            } else if (datoSeleccionado.equals("Departamento, Ciudad, Fecha")) {

                jcFecha.setEnabled(true);
                txtDato.setEnabled(false);
                jcCiudad.setEnabled(true);
                cbDepartamento.setEnabled(true);

            } else if (datoSeleccionado.equals("Pago")) {

                jcFecha.setEnabled(false);
                txtDato.setEnabled(true);
                jcCiudad.setEnabled(false);
                cbDepartamento.setEnabled(true);

            } else if (datoSeleccionado.equals("Departamento")) {

                jcFecha.setEnabled(false);
                txtDato.setEnabled(false);
                jcCiudad.setEnabled(true);
                cbDepartamento.setEnabled(true);

            } else if (datoSeleccionado.equals("Ciudad")) {

                jcFecha.setEnabled(false);
                txtDato.setEnabled(false);
                jcCiudad.setEnabled(true);
                cbDepartamento.setEnabled(true);

            } else if (datoSeleccionado.equals("Fecha")) {

                jcFecha.setEnabled(true);
                txtDato.setEnabled(false);
                jcCiudad.setEnabled(false);
                cbDepartamento.setEnabled(false);

            }
        }
    }//GEN-LAST:event_cbBusquedaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String columna, dato;

        columna = (String) cbBusqueda.getSelectedItem();
        dato = txtDato.getText();

        if (columna.equals("Seleccione")) {

            JOptionPane.showMessageDialog(null, "por favor selecione una columna y "
                    + "digite el dato para filtar");

        } else {

            try {

                if (columna.equals("Vendedor y Fecha")) {

                    String fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();
                    ArrayList<DtoServicio> lista = ctlReportes.listarServiciosPorFiltroVendedor(fecha, vendedor);

                    DefaultTableModel modelo = (DefaultTableModel) tbReporte.getModel();
                    modelo.setRowCount(0);

                    for (DtoServicio dtoServicio : lista) {

                        modelo.addRow(new Object[]{dtoServicio.getAfecha(),
                            dtoServicio.getTecnico(), dtoServicio.getAhora(), dtoServicio.getTipoServicio(),
                            dtoServicio.getNombreNegocio(), dtoServicio.getNombre(), dtoServicio.getApellido(),
                            dtoServicio.getDireccion(), dtoServicio.getCelular(), dtoServicio.getNroFactura(),
                            dtoServicio.getPago(), dtoServicio.getValor(), dtoServicio.getVendedor(),
                            dtoServicio.getMunicipio(), dtoServicio.getCiudad()});

                    }

                } else if (columna.equals("Departamento, Ciudad")) {

                    String departamento = (String) cbDepartamento.getSelectedItem();
                    String ciudad = (String) jcCiudad.getSelectedItem();

                    ArrayList<DtoServicio> lista = ctlReportes.listaServicioDepartamentoCiudad(columna, departamento, ciudad);

                    DefaultTableModel modelo = (DefaultTableModel) tbReporte.getModel();
                    modelo.setRowCount(0);

                    for (DtoServicio dtoServicio : lista) {

                        modelo.addRow(new Object[]{dtoServicio.getAfecha(),
                            dtoServicio.getTecnico(), dtoServicio.getAhora(), dtoServicio.getTipoServicio(),
                            dtoServicio.getNombreNegocio(), dtoServicio.getNombre(), dtoServicio.getApellido(),
                            dtoServicio.getDireccion(), dtoServicio.getCelular(), dtoServicio.getNroFactura(),
                            dtoServicio.getPago(), dtoServicio.getValor(), dtoServicio.getVendedor(),
                            dtoServicio.getMunicipio(), dtoServicio.getCiudad()});

                    }

                } else if (columna.equals("Departamento, Ciudad, Fecha")) {

                    String departamento = (String) cbDepartamento.getSelectedItem();
                    String ciudad = (String) jcCiudad.getSelectedItem();
                    String fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();

                    ArrayList<DtoServicio> lista = ctlReportes.listaServicioDepartamentoCiudadFecha(columna, departamento, ciudad, fecha);

                    DefaultTableModel modelo = (DefaultTableModel) tbReporte.getModel();
                    modelo.setRowCount(0);

                    for (DtoServicio dtoServicio : lista) {

                        modelo.addRow(new Object[]{dtoServicio.getAfecha(),
                            dtoServicio.getTecnico(), dtoServicio.getAhora(), dtoServicio.getTipoServicio(),
                            dtoServicio.getNombreNegocio(), dtoServicio.getNombre(), dtoServicio.getApellido(),
                            dtoServicio.getDireccion(), dtoServicio.getCelular(), dtoServicio.getNroFactura(),
                            dtoServicio.getPago(), dtoServicio.getValor(), dtoServicio.getVendedor(),
                            dtoServicio.getMunicipio(), dtoServicio.getCiudad()});

                    }

                } else {

                    String departamento = (String) cbDepartamento.getSelectedItem();
                    String ciudad = (String) jcCiudad.getSelectedItem();
                    String fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();

                    ArrayList<DtoServicio> lista = ctlReportes.listaServicioFiltro(columna, departamento, ciudad, fecha, dato);

                    DefaultTableModel modelo = (DefaultTableModel) tbReporte.getModel();
                    modelo.setRowCount(0);

                    for (DtoServicio dtoServicio : lista) {

                        modelo.addRow(new Object[]{dtoServicio.getAfecha(),
                            dtoServicio.getTecnico(), dtoServicio.getAhora(), dtoServicio.getTipoServicio(),
                            dtoServicio.getNombreNegocio(), dtoServicio.getNombre(), dtoServicio.getApellido(),
                            dtoServicio.getDireccion(), dtoServicio.getCelular(), dtoServicio.getNroFactura(),
                            dtoServicio.getPago(), dtoServicio.getValor(), dtoServicio.getVendedor(),
                            dtoServicio.getMunicipio(), dtoServicio.getCiudad()});

                    }

                }

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String columna, dato;

        columna = (String) cbBusqueda.getSelectedItem();
        dato = txtDato.getText();

        if (columna.equals("Seleccione")) {

            JOptionPane.showMessageDialog(null, "por favor selecione una columna y "
                    + "digite el dato para filtar");

        } else {
            
            try {
                
                if (columna.equals("Vendedor y Fecha")) {

                    //String fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();
                    

                } else if (columna.equals("Departamento, Ciudad")) {

                    String departamento = (String) cbDepartamento.getSelectedItem();
                    String ciudad = (String) jcCiudad.getSelectedItem();
                    
                    ctlReportes.reporte(columna, departamento, ciudad, ciudad, dato);

                } else if (columna.equals("Departamento, Ciudad, Fecha")) {

                    String departamento = (String) cbDepartamento.getSelectedItem();
                    String ciudad = (String) jcCiudad.getSelectedItem();
                    String fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();

                    ctlReportes.reporte(columna, departamento, ciudad, fecha, dato);

                } else {

                    String departamento = (String) cbDepartamento.getSelectedItem();
                    String ciudad = (String) jcCiudad.getSelectedItem();
                    String fecha = ((JTextField) jcFecha.getDateEditor().getUiComponent()).getText();
                    
                    ctlReportes.reporte(columna, departamento, ciudad, fecha, dato);
                    JOptionPane.showMessageDialog(null, "se ha generado el reporte");

                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
        }

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbBusqueda;
    private javax.swing.JComboBox<String> cbDepartamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcCiudad;
    private com.toedter.calendar.JDateChooser jcFecha;
    private javax.swing.JTable tbReporte;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
