/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CtlServicio;
import DTO.DtoServicio;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class FrmServicioPendiente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmServicioPendiente
     */
    CtlServicio ctlServicio;

    public FrmServicioPendiente() {
        initComponents();
        this.setSize(new Dimension(1720, 600));
        this.setTitle("Lista Pendientes");
        ctlServicio = new CtlServicio();
        listar();
    }

    public void listar() {

        ArrayList<DtoServicio> lista = ctlServicio.listarServiciosPendiente();

        DefaultTableModel modelo = (DefaultTableModel) tbServicios.getModel();
        modelo.setRowCount(0);

        for (DtoServicio dtoServicio : lista) {

            modelo.addRow(new Object[]{dtoServicio.getAfecha(),
                dtoServicio.getTecnico(), dtoServicio.getAhora(),
                dtoServicio.getTipoServicio(), dtoServicio.getNombreNegocio(), dtoServicio.getNombre(),
                dtoServicio.getApellido(), dtoServicio.getDireccion(), dtoServicio.getMunicipio(),
                dtoServicio.getCiudad(), dtoServicio.getCelular(),
                dtoServicio.getEncargado(), dtoServicio.getCelEncargado(), dtoServicio.getValor(),
                dtoServicio.getaObservacion(), dtoServicio.getNroFactura(), dtoServicio.getRefuerzo(),
                dtoServicio.getPeriocidad(), dtoServicio.getProxFecha(), dtoServicio.getPago(),
                dtoServicio.getVendedor(), dtoServicio.getTiempoServicio(),
                dtoServicio.getCalidadLlamada(), dtoServicio.getGestionLlamada()});

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbServicios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha Agenda", "Tecnico", "Hora", "Tipo de Servicio", "Razon Social", "Nombre", "Apellido", "Direccion", "Departamento", "Ciudad", "Telefono", "Encargado", "Telefono Encargado", "Valor", "# Factura", "Nro Servicio", "Refuerzo", "Periocidad", "Proxima Fecha", "Pago", "Vendedor", "Tiempo del servicio", "Llamada de Calidad", "Gestion de Llamada"
            }
        ));
        tbServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbServiciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbServicios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1670, 480));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Servicios Pendientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbServiciosMouseClicked
        // TODO add your handling code here:

        String factura, direccion;
        int seleccionar;

        seleccionar = tbServicios.rowAtPoint(evt.getPoint());

        factura = String.valueOf(tbServicios.getValueAt(seleccionar, 15));

        ctlServicio.almacenarDatos1(factura, "servicio");

        FrmMenuCliente gestionar = new FrmMenuCliente();
        gestionar.setVisible(true);
    }//GEN-LAST:event_tbServiciosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbServicios;
    // End of variables declaration//GEN-END:variables
}
