/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.CtlUsuario;
import Modelo.Usuario;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author ALAN
 */
public class FrmUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmUsuario
     */
    CtlUsuario ctlUsuario;
    public String usuarioIniciado;

    public FrmUsuario() {
        initComponents();
        this.setSize(new Dimension(410, 450));
        this.setTitle("Gestionar Usuarios");
        cargarCombo1();
        ctlUsuario = new CtlUsuario();
        Inicio usuarioInicio = new Inicio();
        usuarioIniciado = usuarioInicio.usuarioIniciado;
        botonesInabilitar(verificar(usuarioIniciado));
    }

    public void cargarCombo1() {
        CbEstado.removeAllItems();
        CbEstado.addItem("Seleccione");
        CbEstado.addItem("Activo");
        CbEstado.addItem("Inactivo");
    }

    public void limpiarCampos() {

        txtApellidoEmpleado.setText("");
        txtNombreEmpleado.setText("");
        txtNombreUsuario.setText("");
        txtPw.setText("");
        txtPwConfirmacion.setText("");
        cargarCombo1();
    }

    public void botonesInabilitar(boolean estado) {

        btnGuardar.setEnabled(estado);
        btnBuscar.setEnabled(estado);
        btnEditar.setEnabled(estado);
        btnEliminar.setEnabled(estado);

    }

    public Boolean verificar(String usuario) {

        Usuario usu = ctlUsuario.tipoUsuario(usuario);

        if (usu.getTipo_Usuario().equals("Empleado")) {

            JOptionPane.showMessageDialog(null, "usted no es administrador");
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtPw = new javax.swing.JTextField();
        txtPwConfirmacion = new javax.swing.JTextField();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtApellidoEmpleado = new javax.swing.JTextField();
        CbEstado = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gestionar Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 73, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 123, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Confirmar Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 173, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nombre Empleado");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 223, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Apellido Empleado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 273, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Estado");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 323, -1, -1));
        getContentPane().add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 150, -1));
        getContentPane().add(txtPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 150, -1));
        getContentPane().add(txtPwConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 150, -1));
        getContentPane().add(txtNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 150, -1));
        getContentPane().add(txtApellidoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 150, -1));

        CbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 150, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 373, -1, -1));

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 373, -1, -1));

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 373, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 373, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        String nombreUsuario, pw, confirmarPw, nombre, apellido, estado;

        nombreUsuario = txtNombreUsuario.getText();
        pw = txtPw.getText();
        confirmarPw = txtPwConfirmacion.getText();
        nombre = txtNombreEmpleado.getText();
        apellido = txtApellidoEmpleado.getText();
        estado = (String) CbEstado.getSelectedItem();

        if (nombreUsuario.isEmpty() || pw.isEmpty() || confirmarPw.isEmpty()
                || nombre.isEmpty() || apellido.isEmpty() || estado.equals("Seleccione")) {

            JOptionPane.showMessageDialog(null, "porfavor llenar los "
                    + "datos del usuario que quiere registrar");

        } else {

            try {

                if (pw.equals(confirmarPw)) {

                    Usuario usuario = new Usuario(0, nombreUsuario, pw,
                            "Empleado", estado, nombre, apellido);
                    ctlUsuario.guardarUsuario(usuario);
                    JOptionPane.showMessageDialog(null, "se ha guardado correctamente");
                    limpiarCampos();

                } else {
                    JOptionPane.showMessageDialog(null, "verificar la Contraseña");
                }

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e.getMessage());

            }

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        String usuario;

        usuario = txtNombreUsuario.getText();

        if (usuario.isEmpty()) {

            JOptionPane.showMessageDialog(null, "buscar por el nombre del usuario");

        } else {

            try {

                Usuario u = ctlUsuario.buscarUsuario(usuario);
                txtApellidoEmpleado.setText(u.getApellido());
                txtNombreEmpleado.setText(u.getNombre());
                txtNombreUsuario.setText(u.getNombre_Usuario());
                txtPw.setText(u.getPw());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:

        String nombreUsuario, pw, confirmarPw, nombre, apellido, estado;

        nombreUsuario = txtNombreUsuario.getText();
        pw = txtPw.getText();
        confirmarPw = txtPwConfirmacion.getText();
        nombre = txtNombreEmpleado.getText();
        apellido = txtApellidoEmpleado.getText();
        estado = (String) CbEstado.getSelectedItem();

        if (nombreUsuario.isEmpty() || pw.isEmpty() || confirmarPw.isEmpty()
                || nombre.isEmpty() || apellido.isEmpty() || estado.equals("Seleccione")) {

            JOptionPane.showMessageDialog(null, "porfavor llenar los "
                    + "datos del usuario que quiere registrar");

        } else {

            try {

                if (pw.equals(confirmarPw)) {

                    Usuario usuario = new Usuario(0, nombreUsuario, pw,
                            "Empleado", estado, nombre, apellido);
                    ctlUsuario.editarUsuario(usuario);
                    JOptionPane.showMessageDialog(null, "se ha editado correctamente");
                    limpiarCampos();

                } else {
                    JOptionPane.showMessageDialog(null, "verificar la Contraseña");
                }

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e.getMessage());

            }

        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        String nombreUsuario;

        nombreUsuario = txtNombreUsuario.getText();

        if (nombreUsuario.isEmpty()) {

            JOptionPane.showMessageDialog(null, "para eliminar busque el usuario y eliminelo");

        } else {

            try {

                ctlUsuario.eliminarUsuario(nombreUsuario);
                JOptionPane.showMessageDialog(null, "se ha eliminado correctamente");
                limpiarCampos();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbEstado;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtApellidoEmpleado;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtPw;
    private javax.swing.JTextField txtPwConfirmacion;
    // End of variables declaration//GEN-END:variables
}
